/*
 * SINAV VERİSİ — Diş Hekimliği / Sabit Protetik
 * ---------------------------------------------
 * Soru tipleri:
 *   - "mc"   : çoktan seçmeli. options + answer (doğru şıkkın TAM metni). Otomatik puanlanır.
 *
 * explanation: opsiyonel, yanlış cevapta gösterilir (özellikle Doğru/Yanlış sorularındaki düzeltmeler).
 *
 * Kaynak: 5 adet "CEVAP ANAHTARLI" sınav PDF'i.
 */
window.EXAMS = [
  /* ============================================================ */
  /* SINAV 1 — Ders 3: Sabit Protetik Diş Tedavisine Giriş        */
  /* ============================================================ */
  {
    id: "ders3-giris",
    title: "Ders 3 — Sabit Protetiğe Giriş",
    description: "Yapım aşamaları, klinik muayene, preparasyon, retraksiyon ve ölçü.",
    questions: [
      // --- BÖLÜM A: Çoktan Seçmeli ---
      { type: "mc", question: "Sabit protetik tedavide iyi bir teşhis için dikkat edilmesi gereken 4 unsurdan biri DEĞİLDİR?",
        options: ["Anamnez (hikaye)", "Ağız içi ve ağız dışı muayene", "Radyografik muayene", "Diagnostik (tanı) modeller", "Cila işlemi"], answer: "Cila işlemi" },
      { type: "mc", question: "Sağlıklı diş eti cep derinliği normalde kaç mm olmalıdır?",
        options: ["0 – 1 mm", "1 – 3 mm", "3 – 5 mm", "4 – 6 mm", "5 – 8 mm"], answer: "1 – 3 mm" },
      { type: "mc", question: "Aşağıdaki kron tiplerinden hangisi için EN AZ miktarda diş dokusu uzaklaştırılır?",
        options: ["Tam porselen kuron", "Metal destekli kron", "Tam metal kron", "Zirkonyum kron", "Lamine veneer"], answer: "Tam metal kron" },
      { type: "mc", question: "Aşağıdaki kron tiplerinden hangisi için EN FAZLA diş dokusu uzaklaştırılması gerekir?",
        options: ["Tam metal kron", "Metal destekli kron", "Tam porselen kuron", "İnley", "Onley"], answer: "Tam porselen kuron" },
      { type: "mc", question: "Net ölçü alabilmek için dişetinin dişten kısa süreliğine (5–10 dk) yatay ve dikey yönde uzaklaştırılması işlemine ne ad verilir?",
        options: ["Preparasyon", "Retraksiyon", "Modelasyon", "Simantasyon", "Cila"], answer: "Retraksiyon" },
      { type: "mc", question: "Aşağıdakilerden hangisi bir hidrokolloid ölçü maddesidir?",
        options: ["Silikon", "Polieter", "Aljinat", "Polisülfit", "Üretan dimetakrilat"], answer: "Aljinat" },
      { type: "mc", question: "Aşağıdakilerden hangisi bir elastomer ölçü maddesidir?",
        options: ["Aljinat", "Silikon", "Agar", "Alçı", "Mum"], answer: "Silikon" },
      { type: "mc", question: "Silikon ölçü maddesi kaç farklı kıvamda bulunur?",
        options: ["1", "2", "3", "4", "5"], answer: "3" },
      { type: "mc", question: "Aljinat ölçü maddesi ile ilgili aşağıdaki ifadelerden hangisi YANLIŞTIR?",
        options: ["Deniz canlılarından (yosun) elde edilir", "Sertleştikten sonra tekrar kullanılabilir", "Toz ve su ölçeği ile karıştırılır", "Hem sabit hem hareketli protezde kullanılır", "Aşamaları renk değişimi ile kontrol edilebilir"], answer: "Sertleştikten sonra tekrar kullanılabilir" },
      { type: "mc", question: "Bir tam metal kronun yapım aşamalarının DOĞRU sıralaması hangisidir?",
        options: ["Klinik muayene → Ölçü → Preparasyon → Model → Modelasyon → Döküm → Cila", "Klinik muayene → Preparasyon → Ölçü → Model → Modelasyon → Döküm → Cila", "Preparasyon → Klinik muayene → Ölçü → Model → Döküm → Modelasyon → Cila", "Klinik muayene → Preparasyon → Model → Ölçü → Modelasyon → Cila → Döküm", "Ölçü → Klinik muayene → Preparasyon → Model → Cila → Döküm"], answer: "Klinik muayene → Preparasyon → Ölçü → Model → Modelasyon → Döküm → Cila" },
      { type: "mc", question: "Basamaklı preparasyonun amaçları arasında aşağıdakilerden hangisi YER ALMAZ?",
        options: ["Çiğneme kuvvetinin dişe iletimini iyileştirmek", "Kronun statik gücünü artırmak", "Krona yeterli kalınlıkta malzeme sağlamak", "Estetik sağlamak", "Dişeti cep derinliğini artırmak"], answer: "Dişeti cep derinliğini artırmak" },
      { type: "mc", question: "Preparasyon işleminde aşağıdaki aletlerden hangisi KULLANILMAZ?",
        options: ["Yüksek devirli aeratör", "Düşük devirli mikromotor (angldurva)", "Elmas frez", "Karbit (karbid) frez", "Ölçü kaşığı"], answer: "Ölçü kaşığı" },
      { type: "mc", question: "Ölçü işlemi ile elde edilen kopya, niteliği bakımından aşağıdakilerden hangisidir?",
        options: ["Pozitif kopya", "Negatif kopya", "Birebir metal kopya", "Dijital tarama", "Alçı model"], answer: "Negatif kopya" },
      { type: "mc", question: "Aşağıdakilerden hangisi ölçü maddelerinin seçiminde dikkate alınan özelliklerden biri DEĞİLDİR?",
        options: ["Sertleşme süresi", "Islanabilme", "Detay verebilme", "Yoğunluk", "Dişeti cep derinliği"], answer: "Dişeti cep derinliği" },

      // --- BÖLÜM B: Çoktan Seçmeli ---
      { type: "mc", question: "Sabit protez yapım aşamaları klinik muayene ile başlar ve hangi işlem ile sona erer?",
        options: ["Cila", "Ölçü", "Preparasyon", "Döküm", "Modelasyon"], answer: "Cila" },
      { type: "mc", question: "Aşağıdakilerden hangisi iyi bir teşhis için dikkat edilmesi gereken 4 unsurdan biridir?",
        options: ["Anamnez (hikaye)", "Cila işlemi", "Simantasyon", "Retraksiyon", "Döküm"], answer: "Anamnez (hikaye)" },
      { type: "mc", question: "Sağlıklı dişeti cep derinliği kaç mm olmalıdır?",
        options: ["1-3 mm", "0-1 mm", "3-5 mm", "4-6 mm", "5-8 mm"], answer: "1-3 mm" },
      { type: "mc", question: "Kron tipleri için preparasyon miktarı en azdan en çoğa doğru hangi seçenekte sıralanmıştır?",
        options: ["Tam metal kron < Metal destekli kron < Tam porselen kuron", "Tam porselen kuron < Metal destekli kron < Tam metal kron", "Metal destekli kron < Tam metal kron < Tam porselen kuron", "Tam metal kron < Tam porselen kuron < Metal destekli kron", "Tam porselen kuron < Tam metal kron < Metal destekli kron"], answer: "Tam metal kron < Metal destekli kron < Tam porselen kuron" },
      { type: "mc", question: "Dişetini net ölçü için kısa süreliğine uzaklaştırma işlemine ne ad verilir?",
        options: ["Retraksiyon", "Preparasyon", "Modelasyon", "Simantasyon", "Cila"], answer: "Retraksiyon" },
      { type: "mc", question: "İki ana ölçü maddesi ailesi aşağıdakilerden hangisidir?",
        options: ["Hidrokolloidler ve elastomerler", "Silikonlar ve polieterler", "Alçılar ve mumlar", "Agarlar ve aljinatlar", "Metaller ve seramikler"], answer: "Hidrokolloidler ve elastomerler" },
      { type: "mc", question: "Silikon ölçü maddesinin 3 kıvamı koyu, orta ve hangisidir?",
        options: ["Akışkan", "Katı", "Toz", "Macun", "Jel"], answer: "Akışkan" },
      { type: "mc", question: "Aljinat ölçü maddesi neyle karıştırılarak hazırlanır?",
        options: ["Toz ve su ölçeği", "Baz ve katalizör", "Alçı ve su", "Mum ve ısı", "Reçine ve sertleştirici"], answer: "Toz ve su ölçeği" },
      { type: "mc", question: "Ölçü kaşıkları hazırlanış bakımından prefabrik (hazır) ve hangi tip olarak ayrılır?",
        options: ["Kişiye özel", "Metal", "Plastik", "Tek kullanımlık", "Sabit"], answer: "Kişiye özel" },

      // --- BÖLÜM C: Doğru / Yanlış ---
      { type: "mc", question: "Tam porselen kuron, tam metal krona göre daha az diş dokusu uzaklaştırılmasını gerektirir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Daha fazla diş dokusu uzaklaştırılması gerekir." },
      { type: "mc", question: "Kısa veya aşırı konik dişlerde restorasyonun tutuculuğu azalır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Aljinat sertleştikten sonra tekrar kullanılabilir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Sertleşince tekrar kullanılamaz." },
      { type: "mc", question: "Silikon ölçü maddesi baz ve katalizör karışımı ile hazırlanır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Ölçü, çalışılan alanın pozitif kopyasının elde edilmesidir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Ölçü, negatif kopyadır." },
      { type: "mc", question: "Retraksiyon işleminde farklı kalınlıkta özel iplikler kullanılır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Aljinat hem sabit hem de hareketli protez işlemlerinde kullanılabilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Diagnostik (tanı) model, ağız içi muayeneyi destekler ve diş/çeneleri her yönden incelemeyi sağlar.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },

      // --- BÖLÜM D: Çoktan Seçmeli ---
      { type: "mc", question: "Bir tam metal kronun yapım aşamalarının doğru sıralaması hangisidir?",
        options: ["Klinik muayene → Preparasyon → Ölçü → Model eldesi → Modelasyon → Döküm → Cila", "Klinik muayene → Ölçü → Preparasyon → Model eldesi → Modelasyon → Döküm → Cila", "Preparasyon → Klinik muayene → Ölçü → Model eldesi → Döküm → Modelasyon → Cila", "Klinik muayene → Preparasyon → Model eldesi → Ölçü → Cila → Döküm → Modelasyon", "Ölçü → Klinik muayene → Preparasyon → Model eldesi → Cila → Döküm → Modelasyon"], answer: "Klinik muayene → Preparasyon → Ölçü → Model eldesi → Modelasyon → Döküm → Cila" },
      { type: "mc", question: "Aşağıdakilerden hangisi basamaklı preparasyonun amaçlarından biridir?",
        options: ["Kronun statik gücünü artırmak", "Dişeti cep derinliğini artırmak", "Diş rengini değiştirmek", "Ölçü süresini uzatmak", "Simantasyonu engellemek"], answer: "Kronun statik gücünü artırmak" },
      { type: "mc", question: "Aljinat ile silikon ölçü maddelerinin karşılaştırılmasıyla ilgili aşağıdakilerden hangisi DOĞRUDUR?",
        options: ["Aljinat hidrokolloiddir; silikon elastomerdir ve daha iyi detay verir", "Aljinat elastomerdir; silikon hidrokolloiddir", "İkisi de sertleştikten sonra tekrar kullanılabilir", "Silikon toz-su ile, aljinat baz-katalizör ile karışır", "Aljinat silikondan daha iyi detay verir"], answer: "Aljinat hidrokolloiddir; silikon elastomerdir ve daha iyi detay verir" },
      { type: "mc", question: "Retraksiyon işlemi yaklaşık ne kadar süre uygulanır?",
        options: ["5–10 dakika", "1–2 saniye", "30 saniye", "1 saat", "24 saat"], answer: "5–10 dakika" },
    ],
  },

  /* ============================================================ */
  /* SINAV 2 — Ders 4: Klinik Muayene                             */
  /* ============================================================ */
  {
    id: "ders4-klinik-muayene",
    title: "Ders 4 — Klinik Muayene",
    description: "Sabit protezlerin yapım aşamaları: klinik muayene, preparasyon, retraksiyon, ölçü.",
    questions: [
      // A
      { type: "mc", question: "Sabit protez yapımında (tam metal kron üzerinden), klinik muayeneden hemen sonra gelen aşama hangisidir?",
        options: ["Ölçü", "Preparasyon", "Modelasyon", "Döküm", "Cila"], answer: "Preparasyon" },
      { type: "mc", question: "Sabit protez yapım aşamalarının EN SON basamağı hangisidir?",
        options: ["Döküm", "Modelasyon", "Cila", "Ölçü", "Model eldesi"], answer: "Cila" },
      { type: "mc", question: "Diagnostik (tanı) modelin temel amacı aşağıdakilerden hangisidir?",
        options: ["Kronu döküme hazırlamak", "Ağız içi muayeneyi desteklemek; diş ve çeneleri her yönden incelemek", "Dişetini uzaklaştırmak", "Restorasyonu cilalamak", "Ölçü kaşığı seçmek"], answer: "Ağız içi muayeneyi desteklemek; diş ve çeneleri her yönden incelemek" },
      { type: "mc", question: "Kısa veya aşırı konik forma sahip dişlerde aşağıdakilerden hangisi beklenir?",
        options: ["Restorasyonun tutuculuğu artar", "Restorasyonun tutuculuğu azalır", "Dişeti cep derinliği artar", "Preparasyona gerek kalmaz", "Döküm kalitesi artar"], answer: "Restorasyonun tutuculuğu azalır" },
      { type: "mc", question: "Sabit protez için dişlerin frezlerle aşındırılarak küçültülmesi ve restorasyon materyaline yer açılması işlemi nedir?",
        options: ["Retraksiyon", "Modelasyon", "Preparasyon", "Simantasyon", "Cila"], answer: "Preparasyon" },
      { type: "mc", question: "Preparasyonda yatay yönde diş dokusunun uzaklaştırılmasıyla oluşturulan yapı nedir?",
        options: ["Pontik", "Basamak", "Konnektör", "Retiner", "Cep"], answer: "Basamak" },
      { type: "mc", question: "Basamağın genişliği (ince/kalın) neye göre hazırlanır?",
        options: ["Hastanın yaşına", "Dişin rengine", "Kronun yapım malzemesine", "Cep derinliğine", "Ölçü maddesine"], answer: "Kronun yapım malzemesine" },
      { type: "mc", question: "Aşağıdakilerden hangisi preparasyonda kullanılan aletlerden biri DEĞİLDİR?",
        options: ["Yüksek devirli aeratör", "Düşük devirli mikromotor (angldurva)", "Elmas frez", "Karbit (karbid) frez", "Retraksiyon ipliği"], answer: "Retraksiyon ipliği" },
      { type: "mc", question: "Kron tipleri için yapılan preparasyon miktarı (en az → en çok) hangi seçenekte doğru sıralanmıştır?",
        options: ["Tam porselen < Metal destekli < Tam metal", "Metal destekli < Tam metal < Tam porselen", "Tam metal < Metal destekli < Tam porselen", "Tam porselen < Tam metal < Metal destekli", "Tam metal < Tam porselen < Metal destekli"], answer: "Tam metal < Metal destekli < Tam porselen" },
      { type: "mc", question: "Retraksiyon işlemi yaklaşık ne kadar süreyle uygulanır?",
        options: ["1 – 2 saniye", "30 saniye", "5 – 10 dakika", "30 – 60 dakika", "24 saat"], answer: "5 – 10 dakika" },
      { type: "mc", question: "Ölçü işleminin tanımı aşağıdakilerden hangisidir?",
        options: ["Dişin pozitif kopyasını almak", "Çalışılan alan ve komşu dokuların negatif kopyasını elde etmek", "Alçı modeli cilalamak", "Dişetini uzaklaştırmak", "Kronu dökmek"], answer: "Çalışılan alan ve komşu dokuların negatif kopyasını elde etmek" },
      { type: "mc", question: "Aşağıdakilerden hangisi silikon ölçü maddesinin özelliklerinden biri DEĞİLDİR?",
        options: ["Koyu, orta ve akışkan olmak üzere 3 kıvamda bulunur", "İyi detay verir", "Baz ve katalizör karışımı ile hazırlanır", "Daha çok sabit protez işlemlerinde kullanılır", "Sertleştikten sonra tekrar kullanılabilir"], answer: "Sertleştikten sonra tekrar kullanılabilir" },
      { type: "mc", question: "Aljinat ölçü maddesinin çalışma ve sertleşme aşamaları genellikle nasıl kontrol edilir?",
        options: ["Koku ile", "Renk değişikliği ile", "Sıcaklık ölçümü ile", "Ağırlık ile", "Sertlik testi ile"], answer: "Renk değişikliği ile" },
      { type: "mc", question: "Ölçü kaşıkları hazırlanış bakımından nasıl sınıflandırılır?",
        options: ["Metal ve plastik", "Büyük ve küçük", "Prefabrik (hazır) ve kişiye özel", "Sabit ve hareketli", "Tek ve çift"], answer: "Prefabrik (hazır) ve kişiye özel" },

      // B
      { type: "mc", question: "Sabit protez yapım aşamaları klinik muayene ile başlar, hangi işlem ile sona erer?",
        options: ["Cila", "Döküm", "Ölçü", "Modelasyon", "Model eldesi"], answer: "Cila" },
      { type: "mc", question: "Aşağıdakilerden hangisi iyi bir teşhis için gerekli dört unsurdan biri DEĞİLDİR?",
        options: ["Cila işlemi", "Anamnez", "Radyografik muayene", "Diagnostik (tanı) modeller", "Ağız içi/dışı muayene"], answer: "Cila işlemi" },
      { type: "mc", question: "Sağlıklı dişeti cep derinliği kaç mm'dir?",
        options: ["1-3 mm", "0-1 mm", "3-5 mm", "4-6 mm", "5-8 mm"], answer: "1-3 mm" },
      { type: "mc", question: "Preparasyonda diş dokusu yatay yönde uzaklaştırıldığında ne oluşur?",
        options: ["Basamak", "Pontik", "Konnektör", "Retiner", "Cep"], answer: "Basamak" },
      { type: "mc", question: "Dişetini net ölçü için kısa süreliğine uzaklaştırma işlemine ne denir?",
        options: ["Retraksiyon", "Preparasyon", "Simantasyon", "Modelasyon", "Cila"], answer: "Retraksiyon" },
      { type: "mc", question: "Ölçü, çalışılan alanın ne tür kopyasını elde etme işlemidir?",
        options: ["Negatif", "Pozitif", "Dijital", "Metal", "Alçı"], answer: "Negatif" },
      { type: "mc", question: "İki ana ölçü maddesi ailesi aşağıdakilerden hangisidir?",
        options: ["Hidrokolloidler ve elastomerler", "Silikonlar ve mumlar", "Alçılar ve metaller", "Agarlar ve seramikler", "Polieterler ve alçılar"], answer: "Hidrokolloidler ve elastomerler" },
      { type: "mc", question: "Aljinat hangi kaynaktan elde edilir?",
        options: ["Deniz canlılarından (yosun)", "Petrolden", "Ağaç reçinesinden", "Hayvan kemiğinden", "Sentetik polimerden"], answer: "Deniz canlılarından (yosun)" },
      { type: "mc", question: "Ölçü kaşığının temel işlevi aşağıdakilerden hangisidir?",
        options: ["Ölçü maddesini ağıza taşımak ve sertleşirken formunu bozulmadan tutmak", "Dişeti cep derinliğini ölçmek", "Dişi aşındırmak", "Kronu cilalamak", "Dişetini uzaklaştırmak"], answer: "Ölçü maddesini ağıza taşımak ve sertleşirken formunu bozulmadan tutmak" },

      // C
      { type: "mc", question: "Tam metal kron için, tam porselen kurona göre daha fazla diş dokusu uzaklaştırılır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Tam metal kron en az dokuyu gerektirir." },
      { type: "mc", question: "Radyografik muayenede destek dişlerin kron ve kök yapıları değerlendirilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Silikon ölçü maddesi iyi detay verir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Aljinat yalnızca hareketli protez işlemlerinde kullanılır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Hem sabit hem hareketli protezde kullanılır." },
      { type: "mc", question: "Basamaklı preparasyon, yapılacak kronun statik gücünü artırır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Retraksiyon, dişetini kalıcı olarak uzaklaştırma işlemidir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Kısa süreli (5–10 dk) bir işlemdir." },
      { type: "mc", question: "Diagnostik (tanı) model ölçü alınarak alçıdan elde edilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Sabit ve hareketli protez çalışmalarında aynı ölçü kaşıkları kullanılır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Farklı kaşıklar kullanılır." },

      // D
      { type: "mc", question: "Sabit protez yapım aşamalarının doğru sıralaması hangisidir?",
        options: ["Klinik muayene → Preparasyon → Ölçü → Model eldesi → Modelasyon → Döküm → Cila", "Klinik muayene → Ölçü → Preparasyon → Model eldesi → Modelasyon → Döküm → Cila", "Preparasyon → Klinik muayene → Ölçü → Modelasyon → Model eldesi → Döküm → Cila", "Klinik muayene → Preparasyon → Model eldesi → Ölçü → Döküm → Modelasyon → Cila", "Ölçü → Klinik muayene → Preparasyon → Cila → Model eldesi → Döküm → Modelasyon"], answer: "Klinik muayene → Preparasyon → Ölçü → Model eldesi → Modelasyon → Döküm → Cila" },
      { type: "mc", question: "Preparasyonun tanımı aşağıdakilerden hangisidir?",
        options: ["Dişlerin frezlerle aşındırılarak küçültülmesi ve restorasyon materyaline yer açılması", "Dişetinin kısa süreliğine uzaklaştırılması", "Çalışılan alanın negatif kopyasının alınması", "Kronun cilalanması", "Alçı modelin elde edilmesi"], answer: "Dişlerin frezlerle aşındırılarak küçültülmesi ve restorasyon materyaline yer açılması" },
      { type: "mc", question: "Aşağıdakilerden hangisi aljinat ölçü maddesinin bir özelliği DEĞİLDİR?",
        options: ["Sertleştikten sonra tekrar kullanılabilir", "Deniz canlılarından (yosun) elde edilir", "Hem sabit hem hareketli protezde kullanılır", "Aşamaları renk değişimi ile kontrol edilir", "Toz ve su ölçeği ile karıştırılır"], answer: "Sertleştikten sonra tekrar kullanılabilir" },
      { type: "mc", question: "Diagnostik (tanı) modelin amacı aşağıdakilerden hangisidir?",
        options: ["Ölçü alınarak diş ve çenelerin alçı kopyasının elde edilip her yönden incelenmesi", "Destek dişlerin kron ve kök yapılarının röntgenle değerlendirilmesi", "Dişetinin uzaklaştırılması", "Kronun döküme hazırlanması", "Ölçü maddesinin seçilmesi"], answer: "Ölçü alınarak diş ve çenelerin alçı kopyasının elde edilip her yönden incelenmesi" },
    ],
  },

  /* ============================================================ */
  /* SINAV 3 — Ders 5: İnteroklüzal Kayıtlar                      */
  /* ============================================================ */
  {
    id: "ders5-interokluzal",
    title: "Ders 5 — İnteroklüzal Kayıtlar",
    description: "Sentrik ilişki, maksimum kapanış ve lateral interoklüzal kayıt.",
    questions: [
      // A
      { type: "mc", question: "Aşağıdakilerden hangisi bu derste ele alınan üç temel interoklüzal kayıt türünden biri DEĞİLDİR?",
        options: ["Sentrik ilişki kaydı", "Maksimum kapanış kaydı", "Lateral interoklüzal kayıt", "Protrüziv interoklüzal kayıt", "Hepsi temel türlerdendir"], answer: "Protrüziv interoklüzal kayıt" },
      { type: "mc", question: "Sentrik ilişki pozisyonunu belirlemek için kaç teknik kullanılır?",
        options: ["1", "2", "3", "4", "5"], answer: "3" },
      { type: "mc", question: "Aşağıdakilerden hangisi sentrik ilişki kaydı tekniklerinden biri DEĞİLDİR?",
        options: ["Çene ucu rehberliği", "Bilateral (çift taraflı) yönlendirmeli", "Yönlendirmesiz metod", "Tek taraflı (unilateral) zorlamalı metod", "Hepsi tekniktir"], answer: "Tek taraflı (unilateral) zorlamalı metod" },
      { type: "mc", question: "Çene ucu rehberliği tekniğinde kondiller hangi pozisyona yerleştirilir?",
        options: ["En ön ve en alt", "En arka ve en üst", "Ön-üst", "Orta (nötr)", "Lateral"], answer: "En arka ve en üst" },
      { type: "mc", question: "Bilateral (çift taraflı) yönlendirmeli teknikte kondiller hangi pozisyona yönlendirilir?",
        options: ["En arka – en üst", "En arka – en alt", "Daha fizyolojik ön-üst", "Lateral", "Protrüziv"], answer: "Daha fizyolojik ön-üst" },
      { type: "mc", question: "Bilateral yönlendirmeli teknikte hedeflenen ön-üst kondil pozisyonunun temel özelliği nedir?",
        options: ["En retrüziv (en arka) konum olması", "Daha fizyolojik bir konum olması", "Lateral kaymalı olması", "Ağzın tamamen açık konumu olması", "İstirahat konumu olması"], answer: "Daha fizyolojik bir konum olması" },
      { type: "mc", question: "Maksimum kapanış kaydı, aşağıdaki konumlardan hangisini kaydeder?",
        options: ["Dişlerin en fazla temas ettiği (maksimum interküspidasyon) konum", "Ağzın tamamen açık konumu", "Lateral kayma konumu", "Protrüziv konum", "İstirahat (dinlenme) konumu"], answer: "Dişlerin en fazla temas ettiği (maksimum interküspidasyon) konum" },
      { type: "mc", question: "T-scan aşağıdakilerden hangisiyle ilgilidir?",
        options: ["Dijital kapanış (oklüzal) kaydı", "Radyografik inceleme", "Diş rengi seçimi", "Kök kanal tedavisi", "Ölçü maddesi karıştırma"], answer: "Dijital kapanış (oklüzal) kaydı" },
      { type: "mc", question: "İnteroklüzal kayıtların temel amacı aşağıdakilerden hangisidir?",
        options: ["Çenelerin birbirine göre konumunu artikülatöre/laboratuvara doğru aktarmak", "Dişeti rengini belirlemek", "Kök uzunluğunu ölçmek", "Çürük teşhisi koymak", "Dişeti cep derinliğini ölçmek"], answer: "Çenelerin birbirine göre konumunu artikülatöre/laboratuvara doğru aktarmak" },
      { type: "mc", question: "Yönlendirmesiz metodun diğer tekniklerden temel farkı nedir?",
        options: ["Hekimin çeneye kuvvet uygulamaması / yönlendirmemesi", "Kondilleri zorla en arkaya itmesi", "Yalnızca lateral hareket kaydetmesi", "Mutlaka dijital tarama gerektirmesi", "Yalnızca total dişsizlerde kullanılması"], answer: "Hekimin çeneye kuvvet uygulamaması / yönlendirmemesi" },
      { type: "mc", question: "Lateral interoklüzal kayıt, mandibulanın hangi hareketini kaydeder?",
        options: ["Yana (lateral) hareket", "Öne (protrüziv) hareket", "Açma-kapama hareketi", "İstirahat konumu", "Yutkunma hareketi"], answer: "Yana (lateral) hareket" },
      { type: "mc", question: "Çene ucu rehberliği ile bilateral yönlendirmeli teknik arasındaki temel fark nedir?",
        options: ["Biri dijital, diğeri analogdur", "Çene ucu rehberliği kondilleri en arka-en üst; bilateral teknik daha fizyolojik ön-üst pozisyona yönlendirir", "İkisi de kondilleri aynı pozisyona yönlendirir", "Bilateral teknik kondilleri en arkaya iter", "Aralarında fark yoktur"], answer: "Çene ucu rehberliği kondilleri en arka-en üst; bilateral teknik daha fizyolojik ön-üst pozisyona yönlendirir" },

      // B
      { type: "mc", question: "Derste ele alınan üç interoklüzal kayıt türü aşağıdakilerden hangisidir?",
        options: ["Sentrik ilişki, maksimum kapanış ve lateral interoklüzal kayıt", "Sentrik ilişki, protrüziv ve lateral kayıt", "Maksimum kapanış, protrüziv ve istirahat kaydı", "Lateral, protrüziv ve açma-kapama kaydı", "Sentrik ilişki, istirahat ve protrüziv kayıt"], answer: "Sentrik ilişki, maksimum kapanış ve lateral interoklüzal kayıt" },
      { type: "mc", question: "Sentrik ilişki pozisyonunu belirlemek için kaç teknik kullanılır?",
        options: ["3", "1", "2", "4", "5"], answer: "3" },
      { type: "mc", question: "Çene ucu rehberliği tekniği kondilleri hangi pozisyona yerleştirir?",
        options: ["En arka ve en üst", "Ön-üst", "En ön ve en alt", "Lateral", "Orta (nötr)"], answer: "En arka ve en üst" },
      { type: "mc", question: "Bilateral yönlendirmeli teknik kondilleri daha fizyolojik olan hangi pozisyona yönlendirir?",
        options: ["Ön-üst", "En arka-en üst", "En arka-en alt", "Lateral", "Protrüziv"], answer: "Ön-üst" },
      { type: "mc", question: "Yönlendirmesiz metodun temel özelliği aşağıdakilerden hangisidir?",
        options: ["Hekim alt çeneyi yönlendirmez", "Hekim çeneyi zorla arkaya iter", "Yalnızca lateral hareket kaydedilir", "Mutlaka dijital tarama gerekir", "Kondiller ön-üste itilir"], answer: "Hekim alt çeneyi yönlendirmez" },
      { type: "mc", question: "Maksimum kapanış kaydı, dişlerin en fazla temas ettiği hangi konumu kaydeder?",
        options: ["Maksimum interküspidasyon", "Sentrik ilişki", "İstirahat konumu", "Protrüziv konum", "Lateral konum"], answer: "Maksimum interküspidasyon" },
      { type: "mc", question: "Dijital oklüzal (kapanış) kaydı için kullanılan sistem aşağıdakilerden hangisidir?",
        options: ["T-scan", "CAD/CAM", "Artikülatör", "Yüz arkı", "Pantograf"], answer: "T-scan" },

      // C
      { type: "mc", question: "Sentrik ilişki kaydı için yalnızca tek bir teknik vardır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Üç teknik vardır." },
      { type: "mc", question: "Çene ucu rehberliği tekniği kondilleri en arka ve en üst pozisyona getirir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Bilateral yönlendirmeli teknikte hedeflenen ön-üst pozisyon daha fizyolojik kabul edilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Lateral interoklüzal kayıt, açma-kapama hareketini kaydeder.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Yana (lateral) hareketi kaydeder." },
      { type: "mc", question: "T-scan, dijital kapanış kaydında kullanılır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Yönlendirmesiz metotta hekim alt çeneyi zorla arkaya iter.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Hekim çeneyi yönlendirmez." },
      { type: "mc", question: "İnteroklüzal kayıtlar, çenelerin birbirine göre ilişkisini aktarmaya yarar.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },

      // D
      { type: "mc", question: "Aşağıdakilerden hangisi derste anlatılan üç interoklüzal kayıt türünden biri DEĞİLDİR?",
        options: ["Protrüziv interoklüzal kayıt", "Sentrik ilişki kaydı", "Maksimum kapanış kaydı", "Lateral interoklüzal kayıt", "Hepsi temel türlerdendir"], answer: "Protrüziv interoklüzal kayıt" },
      { type: "mc", question: "Aşağıdakilerden hangisi sentrik ilişki kaydı için kullanılan 3 teknikten biri DEĞİLDİR?",
        options: ["Tek taraflı (unilateral) zorlamalı metod", "Çene ucu rehberliği", "Bilateral (çift taraflı) yönlendirmeli", "Yönlendirmesiz metod", "Hepsi tekniktir"], answer: "Tek taraflı (unilateral) zorlamalı metod" },
      { type: "mc", question: "Çene ucu rehberliği ile bilateral yönlendirmeli teknik arasındaki temel fark nedir?",
        options: ["Çene ucu rehberliği kondilleri en arka-en üst; bilateral teknik daha fizyolojik ön-üst pozisyona yönlendirir", "İkisi de kondilleri aynı pozisyona yönlendirir", "Biri dijital, diğeri analogdur", "Bilateral teknik kondilleri en arkaya iter", "Çene ucu rehberliği kondilleri ön-üste yönlendirir"], answer: "Çene ucu rehberliği kondilleri en arka-en üst; bilateral teknik daha fizyolojik ön-üst pozisyona yönlendirir" },
    ],
  },

  /* ============================================================ */
  /* SINAV 4 — Kron ve Köprü Sökümü                               */
  /* ============================================================ */
  {
    id: "kron-kopru-sokum",
    title: "Kron ve Köprü Sökümü",
    description: "Söküm endikasyonları, kesilerek çıkarma, köprü sökümü, kron sökücüler ve tel yöntemi.",
    questions: [
      // A
      { type: "mc", question: "Aşağıdakilerden hangisi bir kron/köprü restorasyonunun sökülme endikasyonlarından biri DEĞİLDİR?",
        options: ["Marjinal uyumun bozulması", "Destek dişte ağrı, apikal lezyon veya periodontal sorun", "Restorasyon materyalinde delinme veya kırılma", "Anterior bölgede renk değişimi (estetik)", "Restorasyonun yeni simante edilmiş olması"], answer: "Restorasyonun yeni simante edilmiş olması" },
      { type: "mc", question: "Yeniden yapılması planlanan bir kron/köprü için hasta açısından EN AZ irritasyon oluşturan çıkarma yöntemi hangisidir?",
        options: ["Kesmeden zorlayarak çıkarma", "Kesilerek çıkarma", "Yalnızca tel ile çıkarma", "Kendiliğinden düşmesini bekleme", "Komşu dişi çekme"], answer: "Kesilerek çıkarma" },
      { type: "mc", question: "Kron kesme işlemi sırasında aşağıdakilerden hangisi YANLIŞTIR?",
        options: ["Hasta konforu için anestezi altında çalışılmalı", "Kesme fasiyal yüzden yapılmalı", "Su soğutması altında yapılmalı", "İşlem oklüzal/insizal yüze uzatılmalı", "Soğutmasız (kuru) çalışılmalı"], answer: "Soğutmasız (kuru) çalışılmalı" },
      { type: "mc", question: "Kron kesme işleminde işlemi kolaylaştırmak için hangi frezin kullanılması önerilir?",
        options: ["Aşınmış çelik frez", "Aşınmamış tungsten rond frez", "Bitirme (beyaz kuşak) frezi", "Taş frez", "Separe (disk)"], answer: "Aşınmamış tungsten rond frez" },
      { type: "mc", question: "Kesme işleminin rahat görülebilmesi için işleme hangi yüzeyden başlanmalıdır?",
        options: ["Palatinal", "Lingual", "Fasiyal (vestibül)", "Proksimal", "Apikal"], answer: "Fasiyal (vestibül)" },
      { type: "mc", question: "Bir köprü restorasyonu kesilerek çıkarılırken DOĞRU yaklaşım hangisidir?",
        options: ["Yalnızca bir destek dişteki kron kesilip kuvvet uygulanır", "Tüm destek dişlerdeki kronlar kesildikten sonra kuvvet uygulanır", "Hiçbir kron kesilmeden vurularak çıkarılır", "Önce kuvvet uygulanır, sonra kesilir", "Yalnızca gövde (pontik) kesilir"], answer: "Tüm destek dişlerdeki kronlar kesildikten sonra kuvvet uygulanır" },
      { type: "mc", question: "Köprüde bir kron kesilip diğeri kesilmeden kuvvet uygulanırsa ne olması beklenir?",
        options: ["Restorasyon kolayca çıkar", "Destek dişlere zarar verilebilir", "Siman güçlenir", "Estetik artar", "Hiçbir olumsuzluk olmaz"], answer: "Destek dişlere zarar verilebilir" },
      { type: "mc", question: "Kesim işleminden sonra restorasyonun çıkarılmasını kolaylaştıran işlem hangisidir?",
        options: ["Marjinlerin içe doğru bükülmesi", "Marjinlerin dışa doğru açılması", "Simanın yeniden uygulanması", "Soğutmanın kesilmesi", "Krona ısı verilmesi"], answer: "Marjinlerin dışa doğru açılması" },
      { type: "mc", question: "Yeniden YAPILMAYACAK bir kron öncelikle nasıl çıkarılmaya çalışılır?",
        options: ["Kesilerek", "Kesmeden", "Mutlaka tel ile", "Diş çekilerek", "Kırılarak"], answer: "Kesmeden" },
      { type: "mc", question: "Tek bir kron, kron sökücü ile çıkarılırken ucun konumu nasıl olmalıdır?",
        options: ["Oklüzal düzleme paralel", "Kron marjinine yerleşmiş ve oklüzal düzleme dik açı yapacak şekilde", "Apikale doğru yönlenmiş", "Embraşüre eğik, marjine değmeden", "Gövdenin ortasına"], answer: "Kron marjinine yerleşmiş ve oklüzal düzleme dik açı yapacak şekilde" },
      { type: "mc", question: "Kron sökücü ile kuvvet nasıl uygulanmalıdır?",
        options: ["Sürekli ve çok hafif", "Aralıklı ve olabildiğince etkili", "Tek seferde maksimum", "Yavaş ve süreklilik olmadan", "Rastgele yönlerde"], answer: "Aralıklı ve olabildiğince etkili" },
      { type: "mc", question: "Mikromotor ucuna takılabilen kron sökücülerin çalışma mekanizması neye dayanır?",
        options: ["Dişi ısıtmaya", "Kron içindeki simanın kırılmasına", "Dişi soğutmaya", "Kron metalini eritmeye", "Marjini kapatmaya"], answer: "Kron içindeki simanın kırılmasına" },
      { type: "mc", question: "Yeniden yapılmayacak bir köprünün çıkarılmasında kullanılan tel yöntemi nasıl uygulanır?",
        options: ["Teller oklüzalden geçirilir", "Embraşürlerden geçirilen teller altta birleştirilerek kuvvet uygulanır", "Tel apikalden sokulur", "Tel ile diş bağlanır", "Tel simanla yapıştırılır"], answer: "Embraşürlerden geçirilen teller altta birleştirilerek kuvvet uygulanır" },
      { type: "mc", question: "Mikromotor kron sökücü uçları nereye yerleştirilebilir?",
        options: ["Yalnızca oklüzal yüze", "Kron marjinine ve embraşürlere", "Yalnızca apikale", "Pontik altına", "Kök yüzeyine"], answer: "Kron marjinine ve embraşürlere" },

      // B
      { type: "mc", question: "Kron/köprü sökümünde kesme işlemi hangi yüzlerden ve su soğutması altında yapılmalıdır?",
        options: ["Fasiyal (vestibül)", "Palatinal", "Lingual", "Proksimal", "Apikal"], answer: "Fasiyal (vestibül)" },
      { type: "mc", question: "Kesme işlemini kolaylaştırmak için aşınmamış hangi frez kullanılır?",
        options: ["Tungsten rond frez", "Aşınmış çelik frez", "Bitirme (beyaz kuşak) frezi", "Taş frez", "Separe (disk)"], answer: "Tungsten rond frez" },
      { type: "mc", question: "Hasta konforu için söküm işlemi ne altında yapılmalıdır?",
        options: ["Anestezi", "Soğutmasız ortam", "Sıcak su", "Vakum", "Kuru hava"], answer: "Anestezi" },
      { type: "mc", question: "Köprü sökümünde bir destek dişin kronu kesildikten sonra ne yapılmalıdır?",
        options: ["Mutlaka diğer destek diş(ler)deki kron(lar) da kesilmelidir", "Hemen kuvvet uygulanır", "Diğer kronlar kesilmeden bırakılır", "Diş çekilir", "Yalnızca pontik kesilir"], answer: "Mutlaka diğer destek diş(ler)deki kron(lar) da kesilmelidir" },
      { type: "mc", question: "Kesim sonrası restorasyonun çıkmasını kolaylaştıran işlem nedir?",
        options: ["Marjinlerin dışa doğru açılması", "Marjinlerin içe doğru bükülmesi", "Simanın yeniden uygulanması", "Krona ısı verilmesi", "Soğutmanın kesilmesi"], answer: "Marjinlerin dışa doğru açılması" },
      { type: "mc", question: "Mikromotor kron sökücülerin çalışma mekanizması neye dayanır?",
        options: ["Kron içindeki simanın kırılmasına", "Dişi ısıtmaya", "Dişi soğutmaya", "Kron metalini eritmeye", "Marjini kapatmaya"], answer: "Kron içindeki simanın kırılmasına" },
      { type: "mc", question: "Yeniden yapılmayacak bir köprüde tel yöntemi nasıl uygulanır?",
        options: ["Embraşürlerden geçirilen teller altta birleştirilerek kuvvet uygulanır", "Teller oklüzalden geçirilir", "Tel apikalden sokulur", "Tel ile diş bağlanır", "Tel simanla yapıştırılır"], answer: "Embraşürlerden geçirilen teller altta birleştirilerek kuvvet uygulanır" },
      { type: "mc", question: "Yeniden yapılması planlanan restorasyonlar için hangi çıkarma yöntemi daha az irritasyon oluşturur?",
        options: ["Kesilerek çıkarma", "Kesmeden zorlayarak çıkarma", "Yalnızca tel ile çıkarma", "Komşu dişi çekme", "Kendiliğinden düşmesini bekleme"], answer: "Kesilerek çıkarma" },

      // C
      { type: "mc", question: "Kron kesme işlemi kuru (soğutmasız) ortamda yapılmalıdır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Su soğutması altında yapılmalıdır." },
      { type: "mc", question: "Restorasyon yeniden yapılacaksa kesilerek çıkarma tercih edilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Köprüde tek kron kesilip diğeri kesilmeden kuvvet uygulamak güvenlidir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Destek dişlere zarar verir." },
      { type: "mc", question: "Anterior bölgede renk değişimi, estetik nedenle bir söküm endikasyonu olabilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Mikromotor kron sökücüler, simanı kırarak etki eder.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Kron sökücü ile kuvvet aralıklı ve olabildiğince etkili uygulanmalıdır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Kesim sonrası marjinlerin içe bükülmesi restorasyonun çıkmasını kolaylaştırır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Marjinler dışa açılmalıdır." },
      { type: "mc", question: "Marjinal uyumun bozulması bir söküm endikasyonudur.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },

      // D
      { type: "mc", question: "Aşağıdakilerden hangisi kron/köprü restorasyonlarının sökülme endikasyonlarından biridir?",
        options: ["Materyalde delinme veya kırılma", "Restorasyonun yeni simante edilmiş olması", "Marjinal uyumun mükemmel olması", "Destek dişin tamamen sağlıklı olması", "Hastanın memnun olması"], answer: "Materyalde delinme veya kırılma" },
      { type: "mc", question: "Bir kronun kesilerek çıkarılması sırasında aşağıdaki kurallardan hangisi YANLIŞTIR?",
        options: ["Soğutmasız (kuru) çalışılmalıdır", "Anestezi altında çalışılır", "Kesme fasiyal yüzden yapılır", "İşlem oklüzal/insizal yüze uzatılır", "Aşınmamış tungsten rond frez kullanılır"], answer: "Soğutmasız (kuru) çalışılmalıdır" },
      { type: "mc", question: "Bir köprünün kesilerek çıkarılmasında doğru sıralama ve nedeni hangisidir?",
        options: ["Önce tüm destek dişlerdeki kronlar kesilir, sonra kuvvet uygulanır; çünkü tek kron kesip kuvvet uygulamak destek dişlere zarar verir", "Önce kuvvet uygulanır, sonra kronlar kesilir", "Yalnızca bir kron kesilip kuvvet uygulanır", "Hiçbir kron kesilmeden vurularak çıkarılır", "Yalnızca gövde (pontik) kesilir"], answer: "Önce tüm destek dişlerdeki kronlar kesilir, sonra kuvvet uygulanır; çünkü tek kron kesip kuvvet uygulamak destek dişlere zarar verir" },
    ],
  },

  /* ============================================================ */
  /* SINAV 5 — Sabit Protezler (Ders 2) Dönem Sonu                */
  /* ============================================================ */
  {
    id: "sabit-protezler-donem-sonu",
    title: "Sabit Protezler — Dönem Sonu",
    description: "Kron/köprü restorasyonları, diş preparasyonu, geçici restorasyonlar.",
    questions: [
      // A
      { type: "mc", question: "Aşağıdakilerden hangisi sabit protezlerin GENEL endikasyonları arasında yer almaz?",
        options: ["Psikolojik nedenler", "Konuşma fonksiyonunun düzeltilmesi", "Fonksiyon ve stabilite", "Yüksek çürük insidansı", "Periodontal nedenler"], answer: "Yüksek çürük insidansı" },
      { type: "mc", question: "Tam seramik kuron restorasyonları için dişin insizal/oklüzal kenarında kaç mm preparasyon yapılmalıdır?",
        options: ["0.5 mm", "0.5 – 1 mm", "1.5 – 2 mm", "2.5 – 2.7 mm", "3.5 – 3.7 mm"], answer: "1.5 – 2 mm" },
      { type: "mc", question: "Metal destekli seramik kuronlar için dişlerin fonksiyonel tüberküllerinde en az kaç mm'lik indirgeme yapılmalıdır?",
        options: ["1 mm", "1.5 mm", "2 mm", "2.5 mm", "3.5 mm"], answer: "1.5 mm" },
      { type: "mc", question: "Köprü protezini destek dişe bağlayan, iç yapışma yüzeyini içeren parça aşağıdakilerden hangisidir?",
        options: ["Pontik", "Konnektör", "Retiner", "Gövde", "Embraşur"], answer: "Retiner" },
      { type: "mc", question: "Aşağıdakilerden hangisi geçici sabit restorasyon yapımında kullanılmaz?",
        options: ["Polimetilmetakrilat", "Polietilmetakrilat", "Poliviniletilmetakrilat", "Polivinil siloksan", "Üretan dimetakrilat"], answer: "Polivinil siloksan" },
      { type: "mc", question: "Diş preparasyonunda kabul edilen ideal toplam koniklik (taper) açısı kaç derecedir?",
        options: ["2°", "4°", "6°", "10°", "22°"], answer: "6°" },
      { type: "mc", question: "Kuron-köprü protezlerinde kullanılan geçici restorasyon materyallerinden hangisinin dayanıklılığı en fazladır?",
        options: ["Polivinilmetakrilat", "İzobütil metakrilat", "Polimetilmetakrilat", "Polietilmetakrilat", "Otopolimerizan Bis-GMA kompozit rezin"], answer: "Otopolimerizan Bis-GMA kompozit rezin" },
      { type: "mc", question: "Aşağıdakilerden hangisi ideal geçici kuron-köprü restorasyonlarında bulunması gereken özelliklerden biri DEĞİLDİR?",
        options: ["Oklüzal fonksiyonun devam ettirilmesi", "Periodontal sağlığın korunması", "Pozisyonel stabilitenin sağlanması", "Estetiğin gerekli olmaması", "Kolay temizlenme"], answer: "Estetiğin gerekli olmaması" },
      { type: "mc", question: "Grensiz olup yalnızca bitirme (finishing) amacıyla kullanılan freze karşılık gelen kuşak rengi hangisidir?",
        options: ["Siyah", "Yeşil", "Kırmızı", "Sarı", "Beyaz"], answer: "Beyaz" },
      { type: "mc", question: "Dik açılı, köşeli, bizotajsız ve genellikle 0.5 – 1 mm arasında hazırlanan bitiş çizgisi (basamak) türü hangisidir?",
        options: ["Chamfer", "Knife edge (Bıçak sırtı)", "Shoulder (Künt basamak)", "Bizotajlı chamfer", "Oluk biçimli kenar"], answer: "Shoulder (Künt basamak)" },
      { type: "mc", question: "Tutuculuk (retansiyon) ile ilgili aşağıdaki ifadelerden hangisi DOĞRUDUR?",
        options: ["Apikal ve oblik kuvvetlere karşı direnci ifade eder", "Giriş yolu boyunca restorasyonun yerinden çıkmasına karşı direnci ifade eder", "Yalnızca rezin simanlarla sağlanabilir", "Aksiyel duvarların diverjansı arttıkça artar", "Kron boyu kısaldıkça artar"], answer: "Giriş yolu boyunca restorasyonun yerinden çıkmasına karşı direnci ifade eder" },
      { type: "mc", question: "Eksik dişin yerine konulan, herhangi bir yapışma yüzeyi içermeyen köprü bölümü hangisidir?",
        options: ["Retiner", "Konnektör", "Pontik", "Day", "Post-kor"], answer: "Pontik" },
      { type: "mc", question: "Aşağıdakilerden hangisi sabit protezler için destek dişi seçiminde aranan özelliklerden biri DEĞİLDİR?",
        options: ["Mümkünse vital diş olması", "Dişin asemptomatik olması", "Destek dişte mobilite bulunması", "Kron kaybı varsa post-kor ile desteklenmesi", "Uygun kron/kök oranına sahip olması"], answer: "Destek dişte mobilite bulunması" },
      { type: "mc", question: "Komşu dişlerin kesilmesine ve bu dişlere kron yapılmasına gerek kalmadan, kompozit vb. yapıştırıcı malzeme ile hazırlanan köprü türü hangisidir?",
        options: ["Tam metal köprü", "Vener köprü", "Porselen köprü", "Adeziv köprü", "Zirkonyum köprü"], answer: "Adeziv köprü" },
      { type: "mc", question: "İnley ve onley restorasyonları ile ilgili aşağıdaki ifadelerden hangisi YANLIŞTIR?",
        options: ["İnley küçük ya da orta büyüklükteki lezyonlarda kullanılabilir", "İnley metal veya seramik olabilir", "Onley sabit protezlere ayak olabilecek dirence sahiptir", "Onley tüberküller üzerinde konumlanır", "Onley kron dışı restorasyon olarak kabul edilebilir"], answer: "Onley sabit protezlere ayak olabilecek dirence sahiptir" },

      // B
      { type: "mc", question: "Köprü protezleri temel olarak hangi üç bölümden oluşur?",
        options: ["Retiner, Pontik ve Konnektör", "Retiner, Pontik ve Embraşur", "Pontik, Konnektör ve Post-kor", "Retiner, Day ve Pontik", "Konnektör, Embraşur ve Day"], answer: "Retiner, Pontik ve Konnektör" },
      { type: "mc", question: "Tutuculuk ve direnç hangi kuvvetlere karşı sağlanır?",
        options: ["Tutuculuk giriş yolu boyunca; direnç apikal ve oblik kuvvetlere karşı", "Tutuculuk apikal kuvvetlere; direnç giriş yolu boyunca", "İkisi de yalnızca apikal kuvvetlere karşı", "İkisi de yalnızca lateral kuvvetlere karşı", "Tutuculuk oblik; direnç yutkunma kuvvetlerine karşı"], answer: "Tutuculuk giriş yolu boyunca; direnç apikal ve oblik kuvvetlere karşı" },
      { type: "mc", question: "İdeal koniklik açısı ön dişlerde ve posterior bölgede yaklaşık kaç derecedir?",
        options: ["Ön dişlerde ~10°, posterior bölgede ~22°", "Ön dişlerde ~6°, posterior bölgede ~10°", "Ön dişlerde ~2°, posterior bölgede ~4°", "Ön dişlerde ~22°, posterior bölgede ~10°", "Ön dişlerde ~4°, posterior bölgede ~6°"], answer: "Ön dişlerde ~10°, posterior bölgede ~22°" },
      { type: "mc", question: "Tutuculuk ve direnç açısından önerilen minimum preparasyon (kron) yüksekliği kaç mm'dir?",
        options: ["3 mm", "1 mm", "2 mm", "5 mm", "8 mm"], answer: "3 mm" },
      { type: "mc", question: "Parsiyel kron kapsama oranı anterior, premolar ve molar dişlerde nasıldır?",
        options: ["Anterior ¾, premolar 4/5, molar 7/8", "Anterior 4/5, premolar 7/8, molar ¾", "Anterior 7/8, premolar ¾, molar 4/5", "Anterior ½, premolar ¾, molar 4/5", "Hepsinde ¾"], answer: "Anterior ¾, premolar 4/5, molar 7/8" },
      { type: "mc", question: "Marjin lokalizasyonu nasıl sınıflandırılır?",
        options: ["Subgingival, supragingival ve gingival", "Mezial, distal ve oklüzal", "Fasiyal, lingual ve apikal", "İnsizal, servikal ve apikal", "Vestibül, palatinal ve proksimal"], answer: "Subgingival, supragingival ve gingival" },
      { type: "mc", question: "Diş preparasyonuna genellikle hangi yüzeyden başlanır?",
        options: ["İnsizal veya oklüzal yüzeyden", "Apikal yüzeyden", "Proksimal yüzeyden", "Servikal yüzeyden", "Lingual yüzeyden"], answer: "İnsizal veya oklüzal yüzeyden" },
      { type: "mc", question: "Konvansiyonel simanlar hangi kuvvetlere dayanıklı, hangilerine zayıftır?",
        options: ["Basma kuvvetlerine dayanıklı, çekme/gerilme kuvvetlerine zayıf", "Çekme kuvvetlerine dayanıklı, basma kuvvetlerine zayıf", "Tüm kuvvetlere dayanıklı", "Tüm kuvvetlere zayıf", "Yalnızca oblik kuvvetlere dayanıklı"], answer: "Basma kuvvetlerine dayanıklı, çekme/gerilme kuvvetlerine zayıf" },
      { type: "mc", question: "PMMA polimerizasyon sonrası yaklaşık yüzde kaç büzülme gösterir?",
        options: ["% 8", "% 2", "% 4", "% 15", "% 22"], answer: "% 8" },

      // C
      { type: "mc", question: "Yüksek çürük insidansı, sabit protez yapımı için bir endikasyondur.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Kontrendikasyondur." },
      { type: "mc", question: "Tam kron, parsiyel krona göre daha fazla retansiyon sağlar.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Supragingival marjin, subgingival marjine göre periodonsiyuma daha az zarar verir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Onley, sabit protezlere ayak (destek) olabilecek dirence sahiptir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Bu dirence sahip değildir." },
      { type: "mc", question: "Adeziv köprüde destek dişlere kron yapılması zorunludur.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Komşu dişlere kron yapılmaz." },
      { type: "mc", question: "Eksik dişin anatomik birebir kopyasının gövde olarak yerleştirilmesi hijyenik açıdan doğru bir yaklaşımdır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Hijyenik değildir." },
      { type: "mc", question: "Pontiğin kretle temas eden bölümü mümkün olduğunca dışbükey (konveks) olmalıdır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "PMMA, termal ve kimyasal irritasyona yol açabildiğinden indirekt yöntemde tercih edilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },

      // D
      { type: "mc", question: "Aşağıdakilerden hangisi diş preparasyonunun 5 temel prensibinden biri DEĞİLDİR?",
        options: ["Dişeti cep derinliğinin artırılması", "Diş yapısının korunması", "Tutuculuk ve direncin sağlanması", "Yapısal dayanıklılık", "Kenar uyumu (marjinal bütünlük)"], answer: "Dişeti cep derinliğinin artırılması" },
      { type: "mc", question: "Aşağıdakilerden hangisi köprü protezi tiplerinden biri ve doğru tanımıdır?",
        options: ["Adeziv köprü: komşu dişler kesilmeden yapıştırıcı ile hazırlanan", "Vener köprü: tümü metalden yapılan", "Tam metal köprü: komşu dişler kesilmeden yapıştırılan", "Porselen köprü: vestibül yüzü açık metal", "Adeziv köprü: tüm dişlerin kron ile kaplandığı"], answer: "Adeziv köprü: komşu dişler kesilmeden yapıştırıcı ile hazırlanan" },
      { type: "mc", question: "Aşağıdakilerden hangisi sabit bir restorasyonun tutuculuğunu artırmak için kullanılabilecek bir ek retansiyon yöntemidir?",
        options: ["Oluk ve kutu (box) hazırlamak", "Koniklik açısını artırmak", "Kron boyunu kısaltmak", "Aksiyel duvarları diverjan yapmak", "Marjini subgingival uzatmak"], answer: "Oluk ve kutu (box) hazırlamak" },
      { type: "mc", question: "Aşağıdakilerden hangisi iyi bir geçici restorasyonun taşıması gereken özelliklerden biri DEĞİLDİR?",
        options: ["Estetiğin gerekli olmaması", "Pulpanın korunması", "Konumsal stabilite", "Oklüzal fonksiyon", "Kolay temizlenme"], answer: "Estetiğin gerekli olmaması" },
      { type: "mc", question: "Aşağıdakilerden hangisi subgingival marjin endikasyonlarından biridir?",
        options: ["Estetiğin önemli olduğu ön dişler", "Uzun kron boylu dişler", "Sağlam ve çürüksüz servikal bölge", "Posterior molar dişlerde rutin uygulama", "Supragingival eski restorasyon varlığı"], answer: "Estetiğin önemli olduğu ön dişler" },
    ],
  },

  /* ============================================================ */
  /* SINAV 6 — Ders 6: Ölçü (Kaşıklar, Maddeler, Teknikler)       */
  /* ============================================================ */
  {
    id: "ders6-olcu",
    title: "Ders 6 — Ölçü",
    description: "Ölçü kaşıkları, ölçü maddeleri, aljinat, elastomerler, ölçü teknikleri, CAD/CAM.",
    questions: [
      // A
      { type: "mc", question: "Ölçü; ağız içindeki dişlerin, yumuşak dokuların ve preparasyon sınırlarının ne tür kopyasının elde edilmesidir?",
        options: ["Pozitif kopya", "Negatif kopya", "Dijital pozitif kopya", "Birebir metal kopya", "Alçı model"], answer: "Negatif kopya" },
      { type: "mc", question: "Aşağıdakilerden hangisi HAZIR (prefabrik) ölçü kaşıklarından biri DEĞİLDİR?",
        options: ["Rim-lock metal kaşık", "Sr-Ivotray kaşığı", "H.M. kaşık", "Clan kaşığı", "Sharry tekniği ile hazırlanan kaşık"], answer: "Sharry tekniği ile hazırlanan kaşık" },
      { type: "mc", question: "Aşağıdakilerden hangisi bireysel ölçü kaşıklarının avantajlarından biri DEĞİLDİR?",
        options: ["Anormal büyük/küçük ağızlardan kolay ölçü alınması", "Kennedy 1. ve 2. sınıf vakalar için önerilmesi", "Ölçü maddesinin kalınlığını kontrol etmesi", "Periferik kenarların iyi alınması", "Soğutmalı özel kaşık gerektirmesi"], answer: "Soğutmalı özel kaşık gerektirmesi" },
      { type: "mc", question: "Aşağıdakilerden hangisi günümüzde şahsi (bireysel) kaşık yapımında SIKLIKLA kullanılan materyallerden biridir?",
        options: ["Otopolimerizan akrilik", "Aljinat", "Alçı", "Agar-agar", "Çinko oksit öjenol"], answer: "Otopolimerizan akrilik" },
      { type: "mc", question: "Aşağıdaki ölçü maddelerinden hangisi REVERSIBLE (geri dönüşümlü) gruptadır?",
        options: ["Aljinat", "Polieter", "Agar-agar", "Polivinil siloksan", "Çinko oksit öjenol"], answer: "Agar-agar" },
      { type: "mc", question: "Aşağıdakilerden hangisi ELASTİK bir ölçü maddesi DEĞİLDİR?",
        options: ["Agar hidrokolloid", "Aljinat", "Polieter", "Alçı", "Polivinil siloksan"], answer: "Alçı" },
      { type: "mc", question: "Aljinatın içeriğindeki suyun buharlaşarak büzülmesine ne ad verilir?",
        options: ["İmbibisyon", "Sinerezis", "Polimerizasyon", "Jelasyon", "Tiksotropi"], answer: "Sinerezis" },
      { type: "mc", question: "Aljinatın su emerek şişmesine ne denir?",
        options: ["Sinerezis", "Kontraksiyon", "İmbibisyon", "Distorsiyon", "Sineliz"], answer: "İmbibisyon" },
      { type: "mc", question: "Hızlı sertleşen (Tip 1, fast set) aljinatın sertleşme süresi yaklaşık nedir?",
        options: ["90 saniye", "3 dakika", "5 dakika", "7 dakika", "10 dakika"], answer: "90 saniye" },
      { type: "mc", question: "Aşağıdakilerden hangisi aljinatta boyutsal değişiklik ve distorsiyona neden olan faktörlerden biri DEĞİLDİR?",
        options: ["Su-toz oranı", "Suyun ısısı", "Karıştırma tekniği", "Jelasyon sırasında kaşık hareketi", "Kaşığın rengi"], answer: "Kaşığın rengi" },
      { type: "mc", question: "Aşağıdaki elastomerlerden hangileri HİDROFOBİK karakterdedir?",
        options: ["Polieter ve polisülfit", "Kondensasyon silikon ve polivinil siloksan", "Aljinat ve agar", "Yalnızca polieter", "Yalnızca polisülfit"], answer: "Kondensasyon silikon ve polivinil siloksan" },
      { type: "mc", question: "En yüksek elastik geri dönüm (≈ %99) özelliğine sahip elastomer hangisidir?",
        options: ["Polisülfit", "Kondensasyon silikon", "Polivinil siloksan", "Polieter", "Agar"], answer: "Polivinil siloksan" },
      { type: "mc", question: "Polivinil siloksan (ilave silikon) ile ilgili aşağıdakilerden hangisi YANLIŞTIR?",
        options: ["Sertleşmede yan ürün oluşturmaz", "Lateks/sülfür ile kontaminasyona açıktır", "Polimerizasyon büzülmesi çok azdır", "Sertleşme süresi diğerlerine göre çok uzundur", "İyi detay kopyalar"], answer: "Sertleşme süresi diğerlerine göre çok uzundur" },
      { type: "mc", question: "Polisülfit ölçü maddesinin bir dezavantajı aşağıdakilerden hangisidir?",
        options: ["Lateks eldivenden etkilenmesi", "Sertleşmede yan ürün olarak su açığa çıkması ve tadının kötü olması", "Yırtılmaya dirençsiz olması", "Boyutsal stabilitesinin kötü olması", "Çalışma süresinin çok kısa olması"], answer: "Sertleşmede yan ürün olarak su açığa çıkması ve tadının kötü olması" },
      { type: "mc", question: "Aşağıdakilerden hangisi ÇİFT AŞAMALI elastomer ölçü tekniğidir?",
        options: ["Sandviç tekniği", "Çift karıştırma tekniği", "Heavy body – light body tekniği", "Putty-wash tekniği", "Tek karıştırma (monofaz)"], answer: "Putty-wash tekniği" },
      { type: "mc", question: "CAD/CAM sisteminde 'CAM' kısaltması neyi ifade eder?",
        options: ["Computer Aided Measurement", "Computer Aided Manufacturing", "Computer Assisted Modeling", "Ceramic Added Material", "Computer Aided Margin"], answer: "Computer Aided Manufacturing" },

      // B
      { type: "mc", question: "Ölçü, ağız içindeki yapıların ne tür kopyasının elde edilmesidir?",
        options: ["Negatif", "Pozitif", "Dijital pozitif", "Metal", "Alçı"], answer: "Negatif" },
      { type: "mc", question: "Ölçü maddeleri geri dönüşüme göre nasıl ikiye ayrılır?",
        options: ["Reversible (ör. agar-agar) ve irreversible (ör. aljinat)", "Reversible (ör. aljinat) ve irreversible (ör. agar-agar)", "Elastik ve inelastik", "Hidrofilik ve hidrofobik", "Tek aşamalı ve çift aşamalı"], answer: "Reversible (ör. agar-agar) ve irreversible (ör. aljinat)" },
      { type: "mc", question: "Aljinat suyla karıştırıldığında ne oluşur?",
        options: ["Çözünmeyen kalsiyum aljinat lifleri", "Çözünür sodyum aljinat", "Agar jeli", "Silikon ağı", "Çinko oksit kristalleri"], answer: "Çözünmeyen kalsiyum aljinat lifleri" },
      { type: "mc", question: "Aljinatta suyun buharlaşıp büzülmesine ve su emerek şişmesine sırasıyla ne ad verilir?",
        options: ["Sinerezis ve imbibisyon", "İmbibisyon ve sinerezis", "Jelasyon ve sinerezis", "Sinerezis ve kontraksiyon", "İmbibisyon ve distorsiyon"], answer: "Sinerezis ve imbibisyon" },
      { type: "mc", question: "Silikon esaslı elastomerlerin en yoğun, hamur kıvamındaki tipine ne denir?",
        options: ["Putty", "Light body", "Wash", "Monofaz", "Heavy body"], answer: "Putty" },
      { type: "mc", question: "Hidrofilik elastomerler polieter ve hangisidir?",
        options: ["Polisülfit", "Polivinil siloksan", "Kondensasyon silikon", "Agar", "Aljinat"], answer: "Polisülfit" },
      { type: "mc", question: "CAD ve CAM kısaltmaları ne anlama gelir?",
        options: ["CAD: Computer Aided Design; CAM: Computer Aided Manufacturing", "CAD: Computer Aided Manufacturing; CAM: Computer Aided Design", "CAD: Ceramic Aided Design; CAM: Computer Added Material", "CAD: Computer Assisted Drawing; CAM: Computer Aided Margin", "CAD: Computer Aided Measurement; CAM: Ceramic Aided Modeling"], answer: "CAD: Computer Aided Design; CAM: Computer Aided Manufacturing" },
      { type: "mc", question: "Silikon esaslı ölçülerde alçı dökmek için en uygun süre ilk kaç dakikadır?",
        options: ["30", "5", "10", "60", "90"], answer: "30" },

      // C
      { type: "mc", question: "Ölçü, ağız yapılarının pozitif kopyasının elde edilmesidir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Negatif kopyadır." },
      { type: "mc", question: "Aljinat, günümüzde bölümlü protezler için en çok kullanılan elastik ölçü maddesidir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Agar-agar günümüzde ağızdan ölçü alımında yaygın olarak kullanılır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Pratik değildir; daha çok duplikat modelde kullanılır." },
      { type: "mc", question: "Polivinil siloksan, en yüksek elastik geri dönüm özelliğine sahip elastomerdir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Polisülfit ölçü maddesinin tadı oldukça iyidir.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Tadı oldukça kötüdür." },
      { type: "mc", question: "Viskozite arttıkça ölçü maddesinin detay kayıt kabiliyeti azalır.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },
      { type: "mc", question: "Putty-wash tekniğinde akıcı ölçü maddesi putty'nin yalnızca tek tarafına yayılmalıdır.",
        options: ["Doğru", "Yanlış"], answer: "Yanlış", explanation: "Her tarafına yayılmalıdır." },
      { type: "mc", question: "Aljinat ölçü, %100 nemli ortamda en fazla 30 dakika bekletilebilir.",
        options: ["Doğru", "Yanlış"], answer: "Doğru" },

      // D
      { type: "mc", question: "Aşağıdakilerden hangisi ölçü maddelerinde bulunması gereken bir özelliktir?",
        options: ["Dokuları ayrıntılı kaydedebilmesi", "Irritan ve toksik olması", "Boyutsal değişikliğinin fazla olması", "Model materyali ile kimyasal etkileşime girmesi", "Sertleşme süresinin kontrol edilememesi"], answer: "Dokuları ayrıntılı kaydedebilmesi" },
      { type: "mc", question: "Aşağıdakilerden hangisi aljinatta boyutsal değişiklik ve distorsiyona neden olan faktörlerden biri DEĞİLDİR?",
        options: ["Kaşığın rengi", "Su-toz oranı", "Suyun ısısı", "Karıştırma tekniği", "Jelasyon sırasında kaşık hareketi"], answer: "Kaşığın rengi" },
      { type: "mc", question: "Aşağıdakilerden hangisi polivinil siloksanın avantajlarından biridir?",
        options: ["Çok az polimerizasyon büzülmesi", "Sertleşmede yan ürün olarak su açığa çıkması", "Kötü tat ve koku", "Boyutsal stabilitesinin düşük olması", "Çok uzun sertleşme süresi"], answer: "Çok az polimerizasyon büzülmesi" },
      { type: "mc", question: "Tek aşamalı ve çift aşamalı elastomer ölçü teknikleri ile ilgili aşağıdakilerden hangisi DOĞRUDUR?",
        options: ["Çift aşamalı (putty-wash): önce putty ile ön ölçü, sonra akıcı wash ile ikinci ölçü alınır", "Tek aşamalı putty-wash; çift aşamalı sandviç tekniğidir", "Tek aşamalı teknikte önce putty, sonra wash ayrı ayrı alınır", "Çift aşamalı teknikte heavy ve light body aynı anda kullanılır", "İki teknik arasında uygulama farkı yoktur"], answer: "Çift aşamalı (putty-wash): önce putty ile ön ölçü, sonra akıcı wash ile ikinci ölçü alınır" },
    ],
  },
];
