// Curated Google Fonts for the app — displayed in the font picker
export interface GoogleFontOption {
  name: string;          // Human-readable name shown in UI
  family: string;        // The CSS font-family name (for font-face reference)
  googleParam: string;   // URL param for Google Fonts API  (after family=)
  fallback: string;      // CSS fallback stack
  category: 'sans-serif' | 'serif' | 'monospace';
  previewText: string;   // Short preview shown in picker card
}

export const GOOGLE_FONTS: GoogleFontOption[] = [

  // ── Sans-Serif ───────────────────────────────────────────────────────────
  {
    name: 'Inter',
    family: 'Inter',
    googleParam: 'Inter:wght@300;400;500;600;700',
    fallback: 'system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    category: 'sans-serif',
    previewText: 'Modern ve temiz',
  },
  {
    name: 'Roboto',
    family: 'Roboto',
    googleParam: 'Roboto:wght@300;400;500;700',
    fallback: 'Arial, Helvetica, sans-serif',
    category: 'sans-serif',
    previewText: 'Sade ve okunabilir',
  },
  {
    name: 'Open Sans',
    family: 'Open Sans',
    googleParam: 'Open+Sans:wght@300;400;500;600;700',
    fallback: 'Arial, Helvetica, sans-serif',
    category: 'sans-serif',
    previewText: 'Nötral ve evrensel',
  },
  {
    name: 'Lato',
    family: 'Lato',
    googleParam: 'Lato:wght@300;400;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Kurumsal ve güvenilir',
  },
  {
    name: 'Poppins',
    family: 'Poppins',
    googleParam: 'Poppins:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Geometrik ve modern',
  },
  {
    name: 'Montserrat',
    family: 'Montserrat',
    googleParam: 'Montserrat:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Zarif ve dikkat çekici',
  },
  {
    name: 'Nunito',
    family: 'Nunito',
    googleParam: 'Nunito:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Yumuşak ve dostane',
  },
  {
    name: 'Raleway',
    family: 'Raleway',
    googleParam: 'Raleway:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Şık ve çağdaş',
  },
  {
    name: 'Ubuntu',
    family: 'Ubuntu',
    googleParam: 'Ubuntu:wght@300;400;500;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Yuvarlak ve arkadaşça',
  },
  {
    name: 'Manrope',
    family: 'Manrope',
    googleParam: 'Manrope:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Dengeli ve profesyonel',
  },
  {
    name: 'Outfit',
    family: 'Outfit',
    googleParam: 'Outfit:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Taze ve modern',
  },
  {
    name: 'Figtree',
    family: 'Figtree',
    googleParam: 'Figtree:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Sıcak ve akıcı',
  },
  {
    name: 'DM Sans',
    family: 'DM Sans',
    googleParam: 'DM+Sans:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Minimal ve dijital',
  },
  {
    name: 'Plus Jakarta Sans',
    family: 'Plus Jakarta Sans',
    googleParam: 'Plus+Jakarta+Sans:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Çağdaş ve dinamik',
  },
  {
    name: 'Work Sans',
    family: 'Work Sans',
    googleParam: 'Work+Sans:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'İş odaklı ve düzenli',
  },
  {
    name: 'Mulish',
    family: 'Mulish',
    googleParam: 'Mulish:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'İnce ve zarif',
  },
  {
    name: 'Rubik',
    family: 'Rubik',
    googleParam: 'Rubik:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Köşeli ve güçlü',
  },
  {
    name: 'Barlow',
    family: 'Barlow',
    googleParam: 'Barlow:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Kondanse ve net',
  },
  {
    name: 'Josefin Sans',
    family: 'Josefin Sans',
    googleParam: 'Josefin+Sans:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Geometrik ve temiz',
  },
  {
    name: 'Quicksand',
    family: 'Quicksand',
    googleParam: 'Quicksand:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Yuvarlak ve sevimli',
  },
  {
    name: 'Cabin',
    family: 'Cabin',
    googleParam: 'Cabin:wght@400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Güçlü ve sağlam',
  },
  {
    name: 'IBM Plex Sans',
    family: 'IBM Plex Sans',
    googleParam: 'IBM+Plex+Sans:wght@300;400;500;600;700',
    fallback: 'Arial, Helvetica, sans-serif',
    category: 'sans-serif',
    previewText: 'Teknik ve açık kaynak',
  },
  {
    name: 'Exo 2',
    family: 'Exo 2',
    googleParam: 'Exo+2:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Fütüristik ve dinamik',
  },
  {
    name: 'Noto Sans',
    family: 'Noto Sans',
    googleParam: 'Noto+Sans:wght@300;400;500;600;700',
    fallback: 'Arial, Helvetica, sans-serif',
    category: 'sans-serif',
    previewText: 'Evrensel ve kapsayıcı',
  },
  {
    name: 'Karla',
    family: 'Karla',
    googleParam: 'Karla:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Yalın ve okunabilir',
  },
  {
    name: 'Hind',
    family: 'Hind',
    googleParam: 'Hind:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Düz ve dengeli',
  },
  {
    name: 'Oxanium',
    family: 'Oxanium',
    googleParam: 'Oxanium:wght@300;400;500;600;700',
    fallback: 'Arial, sans-serif',
    category: 'sans-serif',
    previewText: 'Teknik ve robotik',
  },
  {
    name: 'Space Grotesk',
    family: 'Space Grotesk',
    googleParam: 'Space+Grotesk:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Uzay çağı estetiği',
  },
  {
    name: 'Sora',
    family: 'Sora',
    googleParam: 'Sora:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Yumuşak ve modern',
  },
  {
    name: 'Lexend',
    family: 'Lexend',
    googleParam: 'Lexend:wght@300;400;500;600;700',
    fallback: 'system-ui, sans-serif',
    category: 'sans-serif',
    previewText: 'Okunabilirlik odaklı',
  },

  // ── Serif ────────────────────────────────────────────────────────────────
  {
    name: 'Zilla Slab',
    family: 'Zilla Slab',
    googleParam: 'Zilla+Slab:wght@300;400;500;600;700',
    fallback: 'Georgia, "Times New Roman", serif',
    category: 'serif',
    previewText: 'Klasik ve sofistike',
  },
  {
    name: 'Merriweather',
    family: 'Merriweather',
    googleParam: 'Merriweather:wght@300;400;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Baskı kalitesi',
  },
  {
    name: 'Playfair Display',
    family: 'Playfair Display',
    googleParam: 'Playfair+Display:wght@400;500;600;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Lüks ve editoryal',
  },
  {
    name: 'Lora',
    family: 'Lora',
    googleParam: 'Lora:wght@400;500;600;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Zarif ve okunabilir',
  },
  {
    name: 'PT Serif',
    family: 'PT Serif',
    googleParam: 'PT+Serif:wght@400;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Gazeteci estetiği',
  },
  {
    name: 'Libre Baskerville',
    family: 'Libre Baskerville',
    googleParam: 'Libre+Baskerville:wght@400;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Akademik ve köklü',
  },
  {
    name: 'Crimson Pro',
    family: 'Crimson Pro',
    googleParam: 'Crimson+Pro:wght@300;400;500;600;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'İnce ve edebi',
  },
  {
    name: 'EB Garamond',
    family: 'EB Garamond',
    googleParam: 'EB+Garamond:wght@400;500;600;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Tarihsel ve zarif',
  },
  {
    name: 'Spectral',
    family: 'Spectral',
    googleParam: 'Spectral:wght@300;400;500;600;700',
    fallback: 'Georgia, serif',
    category: 'serif',
    previewText: 'Dijital baskı için',
  },

  // ── Monospace ────────────────────────────────────────────────────────────
  {
    name: 'JetBrains Mono',
    family: 'JetBrains Mono',
    googleParam: 'JetBrains+Mono:wght@300;400;500;600;700',
    fallback: '"Courier New", Courier, monospace',
    category: 'monospace',
    previewText: 'Geliştirici tercihi',
  },
  {
    name: 'Source Code Pro',
    family: 'Source Code Pro',
    googleParam: 'Source+Code+Pro:wght@300;400;500;600;700',
    fallback: '"Courier New", monospace',
    category: 'monospace',
    previewText: 'Teknik ve kesin',
  },
  {
    name: 'Fira Code',
    family: 'Fira Code',
    googleParam: 'Fira+Code:wght@300;400;500;600;700',
    fallback: '"Courier New", Courier, monospace',
    category: 'monospace',
    previewText: 'Ligatürlü ve net',
  },
  {
    name: 'IBM Plex Mono',
    family: 'IBM Plex Mono',
    googleParam: 'IBM+Plex+Mono:wght@300;400;500;600;700',
    fallback: '"Courier New", Courier, monospace',
    category: 'monospace',
    previewText: 'Kurumsal ve net',
  },
  {
    name: 'Roboto Mono',
    family: 'Roboto Mono',
    googleParam: 'Roboto+Mono:wght@300;400;500;600;700',
    fallback: '"Courier New", monospace',
    category: 'monospace',
    previewText: 'Tutarlı ve makine gibi',
  },
  {
    name: 'Space Mono',
    family: 'Space Mono',
    googleParam: 'Space+Mono:wght@400;700',
    fallback: '"Courier New", monospace',
    category: 'monospace',
    previewText: 'Retro ve teknik',
  },
];

export const DEFAULT_FONT_NAME = 'Inter';

export function getFontByName(name: string): GoogleFontOption {
  return (
    GOOGLE_FONTS.find((f) => f.name === name) ??
    GOOGLE_FONTS.find((f) => f.name === DEFAULT_FONT_NAME)!
  );
}
