/**
 * core/ui/icons.tsx — UYGULAMANIN İKON KAYNAĞI (HugeIcons)
 *
 * Neden adaptör: çağrı yerleri Lucide yazımını kullanıyordu (`<Bell size={16} …/>`),
 * HugeIcons'ın API'si ise farklı (`<HugeiconsIcon icon={BellIcon} …/>`). Burada
 * Lucide ADLARI HugeIcons ikonlarına bağlanır → ~276 dosyada yalnız import yolu
 * değişti, JSX'e dokunulmadı. İkon değiştirmek/eklemek TEK yerden yapılır.
 *
 * Kurallar:
 *  - Yeni ikon gerekiyorsa buraya ekle; çağrı yerinde doğrudan @hugeicons'tan alma.
 *  - İkonlar TEK TEK import edilir (`@hugeicons/core-free-icons/<Ad>`); paketin
 *    index'i 7 MB ve Metro ağaç budamıyor — oradan almak pakete hepsini sokar.
 *  - Dental ikonlar (Tooth/Crown/Implant…) core/ui/dentalIcons.tsx'te elle çizili
 *    kalır; kütüphanede karşılıkları yok.
 */
import React from 'react';
import { HugeiconsIcon, type HugeiconsProps } from '@hugeicons/react-native';

import Activity01Icon from '@hugeicons/core-free-icons/Activity01Icon';
import AlarmClockIcon from '@hugeicons/core-free-icons/AlarmClockIcon';
import Alert02Icon from '@hugeicons/core-free-icons/Alert02Icon';
import AlertCircleIcon from '@hugeicons/core-free-icons/AlertCircleIcon';
import AlertDiamondIcon from '@hugeicons/core-free-icons/AlertDiamondIcon';
import ArchiveIcon from '@hugeicons/core-free-icons/ArchiveIcon';
import ArrowDataTransferHorizontalIcon from '@hugeicons/core-free-icons/ArrowDataTransferHorizontalIcon';
import ArrowDown01Icon from '@hugeicons/core-free-icons/ArrowDown01Icon';
import ArrowDownLeft01Icon from '@hugeicons/core-free-icons/ArrowDownLeft01Icon';
import ArrowDownToLineIcon from '@hugeicons/core-free-icons/ArrowDownToLineIcon';
import ArrowLeft01Icon from '@hugeicons/core-free-icons/ArrowLeft01Icon';
import ArrowLeftRightIcon from '@hugeicons/core-free-icons/ArrowLeftRightIcon';
import ArrowRight01Icon from '@hugeicons/core-free-icons/ArrowRight01Icon';
import ArrowTurnBackwardIcon from '@hugeicons/core-free-icons/ArrowTurnBackwardIcon';
import ArrowUp01Icon from '@hugeicons/core-free-icons/ArrowUp01Icon';
import ArrowUpDownIcon from '@hugeicons/core-free-icons/ArrowUpDownIcon';
import ArrowUpLeft01Icon from '@hugeicons/core-free-icons/ArrowUpLeft01Icon';
import ArrowUpRight01Icon from '@hugeicons/core-free-icons/ArrowUpRight01Icon';
import Atom01Icon from '@hugeicons/core-free-icons/Atom01Icon';
import Award01Icon from '@hugeicons/core-free-icons/Award01Icon';
import BadgeCheckIcon from '@hugeicons/core-free-icons/BadgeCheckIcon';
import BanIcon from '@hugeicons/core-free-icons/BanIcon';
import BanknoteIcon from '@hugeicons/core-free-icons/BanknoteIcon';
import BarChartIcon from '@hugeicons/core-free-icons/BarChartIcon';
import BeakerIcon from '@hugeicons/core-free-icons/BeakerIcon';
import BellIcon from '@hugeicons/core-free-icons/BellIcon';
import BellOffIcon from '@hugeicons/core-free-icons/BellOffIcon';
import BellRingIcon from '@hugeicons/core-free-icons/BellRingIcon';
import BikeIcon from '@hugeicons/core-free-icons/BikeIcon';
import BookOpen01Icon from '@hugeicons/core-free-icons/BookOpen01Icon';
import BotIcon from '@hugeicons/core-free-icons/BotIcon';
import BoxIcon from '@hugeicons/core-free-icons/BoxIcon';
import BoxesIcon from '@hugeicons/core-free-icons/BoxesIcon';
import Briefcase01Icon from '@hugeicons/core-free-icons/Briefcase01Icon';
import BrushIcon from '@hugeicons/core-free-icons/BrushIcon';
import Bug01Icon from '@hugeicons/core-free-icons/Bug01Icon';
import Building03Icon from '@hugeicons/core-free-icons/Building03Icon';
import BuildingIcon from '@hugeicons/core-free-icons/BuildingIcon';
import CalculatorIcon from '@hugeicons/core-free-icons/CalculatorIcon';
import Calendar01Icon from '@hugeicons/core-free-icons/Calendar01Icon';
import CalendarCheckIcon from '@hugeicons/core-free-icons/CalendarCheckIcon';
import CalendarClockIcon from '@hugeicons/core-free-icons/CalendarClockIcon';
import CalendarDaysIcon from '@hugeicons/core-free-icons/CalendarDaysIcon';
import CalendarHeartIcon from '@hugeicons/core-free-icons/CalendarHeartIcon';
import CalendarPlusIcon from '@hugeicons/core-free-icons/CalendarPlusIcon';
import Camera01Icon from '@hugeicons/core-free-icons/Camera01Icon';
import CancelCircleIcon from '@hugeicons/core-free-icons/CancelCircleIcon';
import ChartBarIncreasingIcon from '@hugeicons/core-free-icons/ChartBarIncreasingIcon';
import CheckCheckIcon from '@hugeicons/core-free-icons/CheckCheckIcon';
import CheckIcon from '@hugeicons/core-free-icons/CheckIcon';
import CheckListIcon from '@hugeicons/core-free-icons/CheckListIcon';
import CheckmarkCircle01Icon from '@hugeicons/core-free-icons/CheckmarkCircle01Icon';
import CheckmarkCircle02Icon from '@hugeicons/core-free-icons/CheckmarkCircle02Icon';
import CheckmarkSquare01Icon from '@hugeicons/core-free-icons/CheckmarkSquare01Icon';
import ChevronDownIcon from '@hugeicons/core-free-icons/ChevronDownIcon';
import ChevronLeftIcon from '@hugeicons/core-free-icons/ChevronLeftIcon';
import ChevronRightIcon from '@hugeicons/core-free-icons/ChevronRightIcon';
import ChevronUpIcon from '@hugeicons/core-free-icons/ChevronUpIcon';
import CircleArrowDown01Icon from '@hugeicons/core-free-icons/CircleArrowDown01Icon';
import CircleArrowUp01Icon from '@hugeicons/core-free-icons/CircleArrowUp01Icon';
import CircleCheckIcon from '@hugeicons/core-free-icons/CircleCheckIcon';
import CircleDollarSignIcon from '@hugeicons/core-free-icons/CircleDollarSignIcon';
import CircleDotIcon from '@hugeicons/core-free-icons/CircleDotIcon';
import CircleIcon from '@hugeicons/core-free-icons/CircleIcon';
import CircleXIcon from '@hugeicons/core-free-icons/CircleXIcon';
import ClipboardCheckIcon from '@hugeicons/core-free-icons/ClipboardCheckIcon';
import ClipboardIcon from '@hugeicons/core-free-icons/ClipboardIcon';
import ClipboardListIcon from '@hugeicons/core-free-icons/ClipboardListIcon';
import ClipboardXIcon from '@hugeicons/core-free-icons/ClipboardXIcon';
import Clock01Icon from '@hugeicons/core-free-icons/Clock01Icon';
import CloudUploadIcon from '@hugeicons/core-free-icons/CloudUploadIcon';
import CogIcon from '@hugeicons/core-free-icons/CogIcon';
import Coins01Icon from '@hugeicons/core-free-icons/Coins01Icon';
import CookingPotIcon from '@hugeicons/core-free-icons/CookingPotIcon';
import CopyIcon from '@hugeicons/core-free-icons/CopyIcon';
import CornerDownLeftIcon from '@hugeicons/core-free-icons/CornerDownLeftIcon';
import CornerDownRightIcon from '@hugeicons/core-free-icons/CornerDownRightIcon';
import CornerUpLeftIcon from '@hugeicons/core-free-icons/CornerUpLeftIcon';
import CpuIcon from '@hugeicons/core-free-icons/CpuIcon';
import CreditCardIcon from '@hugeicons/core-free-icons/CreditCardIcon';
import CrosshairIcon from '@hugeicons/core-free-icons/CrosshairIcon';
import DatabaseIcon from '@hugeicons/core-free-icons/DatabaseIcon';
import DatabaseZapIcon from '@hugeicons/core-free-icons/DatabaseZapIcon';
import Delete01Icon from '@hugeicons/core-free-icons/Delete01Icon';
import Delete02Icon from '@hugeicons/core-free-icons/Delete02Icon';
import DiamondIcon from '@hugeicons/core-free-icons/DiamondIcon';
import DollarSignIcon from '@hugeicons/core-free-icons/DollarSignIcon';
import Download01Icon from '@hugeicons/core-free-icons/Download01Icon';
import DrillIcon from '@hugeicons/core-free-icons/DrillIcon';
import DropletsIcon from '@hugeicons/core-free-icons/DropletsIcon';
import Edit02Icon from '@hugeicons/core-free-icons/Edit02Icon';
import EqualIcon from '@hugeicons/core-free-icons/EqualIcon';
import EraserIcon from '@hugeicons/core-free-icons/EraserIcon';
import ExternalLinkIcon from '@hugeicons/core-free-icons/ExternalLinkIcon';
import EyeIcon from '@hugeicons/core-free-icons/EyeIcon';
import EyeOffIcon from '@hugeicons/core-free-icons/EyeOffIcon';
import File01Icon from '@hugeicons/core-free-icons/File01Icon';
import FileAddIcon from '@hugeicons/core-free-icons/FileAddIcon';
import FileArchiveIcon from '@hugeicons/core-free-icons/FileArchiveIcon';
import FileAudioIcon from '@hugeicons/core-free-icons/FileAudioIcon';
import FileBoxIcon from '@hugeicons/core-free-icons/FileBoxIcon';
import FileCheckIcon from '@hugeicons/core-free-icons/FileCheckIcon';
import FileClockIcon from '@hugeicons/core-free-icons/FileClockIcon';
import FileDownIcon from '@hugeicons/core-free-icons/FileDownIcon';
import FileEditIcon from '@hugeicons/core-free-icons/FileEditIcon';
import FileMinusIcon from '@hugeicons/core-free-icons/FileMinusIcon';
import FilePlusIcon from '@hugeicons/core-free-icons/FilePlusIcon';
import FileSearchIcon from '@hugeicons/core-free-icons/FileSearchIcon';
import FileSpreadsheetIcon from '@hugeicons/core-free-icons/FileSpreadsheetIcon';
import FileTextIcon from '@hugeicons/core-free-icons/FileTextIcon';
import FileUpIcon from '@hugeicons/core-free-icons/FileUpIcon';
import FileValidationIcon from '@hugeicons/core-free-icons/FileValidationIcon';
import FileVideoIcon from '@hugeicons/core-free-icons/FileVideoIcon';
import FileXIcon from '@hugeicons/core-free-icons/FileXIcon';
import Film01Icon from '@hugeicons/core-free-icons/Film01Icon';
import FilterIcon from '@hugeicons/core-free-icons/FilterIcon';
import FlameIcon from '@hugeicons/core-free-icons/FlameIcon';
import FlashlightIcon from '@hugeicons/core-free-icons/FlashlightIcon';
import FlaskConicalIcon from '@hugeicons/core-free-icons/FlaskConicalIcon';
import FlipHorizontalIcon from '@hugeicons/core-free-icons/FlipHorizontalIcon';
import FocusIcon from '@hugeicons/core-free-icons/FocusIcon';
import Folder01Icon from '@hugeicons/core-free-icons/Folder01Icon';
import FolderOpenIcon from '@hugeicons/core-free-icons/FolderOpenIcon';
import FunnelIcon from '@hugeicons/core-free-icons/FunnelIcon';
import GaugeIcon from '@hugeicons/core-free-icons/GaugeIcon';
import GemIcon from '@hugeicons/core-free-icons/GemIcon';
import GitMergeIcon from '@hugeicons/core-free-icons/GitMergeIcon';
import GlobeIcon from '@hugeicons/core-free-icons/GlobeIcon';
import GraduationCapIcon from '@hugeicons/core-free-icons/GraduationCapIcon';
import Grid3X3Icon from '@hugeicons/core-free-icons/Grid3X3Icon';
import GridIcon from '@hugeicons/core-free-icons/GridIcon';
import GripVerticalIcon from '@hugeicons/core-free-icons/GripVerticalIcon';
import HammerIcon from '@hugeicons/core-free-icons/HammerIcon';
import HandIcon from '@hugeicons/core-free-icons/HandIcon';
import HashIcon from '@hugeicons/core-free-icons/HashIcon';
import HeadphonesIcon from '@hugeicons/core-free-icons/HeadphonesIcon';
import HeartIcon from '@hugeicons/core-free-icons/HeartIcon';
import HelpCircleIcon from '@hugeicons/core-free-icons/HelpCircleIcon';
import HistoryIcon from '@hugeicons/core-free-icons/HistoryIcon';
import Home01Icon from '@hugeicons/core-free-icons/Home01Icon';
import HourglassIcon from '@hugeicons/core-free-icons/HourglassIcon';
import Image01Icon from '@hugeicons/core-free-icons/Image01Icon';
import ImageDownIcon from '@hugeicons/core-free-icons/ImageDownIcon';
import ImageOffIcon from '@hugeicons/core-free-icons/ImageOffIcon';
import ImagePlusIcon from '@hugeicons/core-free-icons/ImagePlusIcon';
import InboxIcon from '@hugeicons/core-free-icons/InboxIcon';
import InfoIcon from '@hugeicons/core-free-icons/InfoIcon';
import KeyRoundIcon from '@hugeicons/core-free-icons/KeyRoundIcon';
import LandmarkIcon from '@hugeicons/core-free-icons/LandmarkIcon';
import LaptopIcon from '@hugeicons/core-free-icons/LaptopIcon';
import Layers01Icon from '@hugeicons/core-free-icons/Layers01Icon';
import LayoutDashboardIcon from '@hugeicons/core-free-icons/LayoutDashboardIcon';
import LayoutGridIcon from '@hugeicons/core-free-icons/LayoutGridIcon';
import LayoutListIcon from '@hugeicons/core-free-icons/LayoutListIcon';
import LightbulbIcon from '@hugeicons/core-free-icons/LightbulbIcon';
import Link02Icon from '@hugeicons/core-free-icons/Link02Icon';
import LinkIcon from '@hugeicons/core-free-icons/LinkIcon';
import ListChecksIcon from '@hugeicons/core-free-icons/ListChecksIcon';
import ListIcon from '@hugeicons/core-free-icons/ListIcon';
import ListPlusIcon from '@hugeicons/core-free-icons/ListPlusIcon';
import ListTodoIcon from '@hugeicons/core-free-icons/ListTodoIcon';
import LoaderIcon from '@hugeicons/core-free-icons/LoaderIcon';
import Loading03Icon from '@hugeicons/core-free-icons/Loading03Icon';
import LocateIcon from '@hugeicons/core-free-icons/LocateIcon';
import LockIcon from '@hugeicons/core-free-icons/LockIcon';
import LogInIcon from '@hugeicons/core-free-icons/LogInIcon';
import LogOutIcon from '@hugeicons/core-free-icons/LogOutIcon';
import MagicWand01Icon from '@hugeicons/core-free-icons/MagicWand01Icon';
import MagnetIcon from '@hugeicons/core-free-icons/MagnetIcon';
import Mail01Icon from '@hugeicons/core-free-icons/Mail01Icon';
import MailWarningIcon from '@hugeicons/core-free-icons/MailWarningIcon';
import MapIcon from '@hugeicons/core-free-icons/MapIcon';
import MapPinCheckIcon from '@hugeicons/core-free-icons/MapPinCheckIcon';
import MapPinIcon from '@hugeicons/core-free-icons/MapPinIcon';
import MapPinOffIcon from '@hugeicons/core-free-icons/MapPinOffIcon';
import Maximize01Icon from '@hugeicons/core-free-icons/Maximize01Icon';
import Megaphone01Icon from '@hugeicons/core-free-icons/Megaphone01Icon';
import MenuIcon from '@hugeicons/core-free-icons/MenuIcon';
import MessageCircleIcon from '@hugeicons/core-free-icons/MessageCircleIcon';
import MessageCirclePlusIcon from '@hugeicons/core-free-icons/MessageCirclePlusIcon';
import MessageSquareIcon from '@hugeicons/core-free-icons/MessageSquareIcon';
import MessagesSquareIcon from '@hugeicons/core-free-icons/MessagesSquareIcon';
import Mic01Icon from '@hugeicons/core-free-icons/Mic01Icon';
import MicOff01Icon from '@hugeicons/core-free-icons/MicOff01Icon';
import MicroscopeIcon from '@hugeicons/core-free-icons/MicroscopeIcon';
import MicrowaveIcon from '@hugeicons/core-free-icons/MicrowaveIcon';
import MinusIcon from '@hugeicons/core-free-icons/MinusIcon';
import MinusSignCircleIcon from '@hugeicons/core-free-icons/MinusSignCircleIcon';
import MonitorIcon from '@hugeicons/core-free-icons/MonitorIcon';
import MoonIcon from '@hugeicons/core-free-icons/MoonIcon';
import MoreHorizontalIcon from '@hugeicons/core-free-icons/MoreHorizontalIcon';
import MoveHorizontalIcon from '@hugeicons/core-free-icons/MoveHorizontalIcon';
import MoveUpRightIcon from '@hugeicons/core-free-icons/MoveUpRightIcon';
import NavigationIcon from '@hugeicons/core-free-icons/NavigationIcon';
import NetworkIcon from '@hugeicons/core-free-icons/NetworkIcon';
import PackageCheckIcon from '@hugeicons/core-free-icons/PackageCheckIcon';
import PackageIcon from '@hugeicons/core-free-icons/PackageIcon';
import PackageOpenIcon from '@hugeicons/core-free-icons/PackageOpenIcon';
import PaintbrushIcon from '@hugeicons/core-free-icons/PaintbrushIcon';
import PaletteIcon from '@hugeicons/core-free-icons/PaletteIcon';
import PanelLeftIcon from '@hugeicons/core-free-icons/PanelLeftIcon';
import PaperclipIcon from '@hugeicons/core-free-icons/PaperclipIcon';
import PauseCircleIcon from '@hugeicons/core-free-icons/PauseCircleIcon';
import PauseIcon from '@hugeicons/core-free-icons/PauseIcon';
import PenLineIcon from '@hugeicons/core-free-icons/PenLineIcon';
import PenTool01Icon from '@hugeicons/core-free-icons/PenTool01Icon';
import PencilEdit01Icon from '@hugeicons/core-free-icons/PencilEdit01Icon';
import PercentIcon from '@hugeicons/core-free-icons/PercentIcon';
import PhoneCallIcon from '@hugeicons/core-free-icons/PhoneCallIcon';
import PhoneIcon from '@hugeicons/core-free-icons/PhoneIcon';
import PieChartIcon from '@hugeicons/core-free-icons/PieChartIcon';
import PinIcon from '@hugeicons/core-free-icons/PinIcon';
import PlayCircleIcon from '@hugeicons/core-free-icons/PlayCircleIcon';
import PlayIcon from '@hugeicons/core-free-icons/PlayIcon';
import PlugIcon from '@hugeicons/core-free-icons/PlugIcon';
import PlusIcon from '@hugeicons/core-free-icons/PlusIcon';
import PlusSignCircleIcon from '@hugeicons/core-free-icons/PlusSignCircleIcon';
import PowerIcon from '@hugeicons/core-free-icons/PowerIcon';
import PrinterIcon from '@hugeicons/core-free-icons/PrinterIcon';
import PuzzleIcon from '@hugeicons/core-free-icons/PuzzleIcon';
import QrCodeIcon from '@hugeicons/core-free-icons/QrCodeIcon';
import ReceiptIcon from '@hugeicons/core-free-icons/ReceiptIcon';
import ReceiptTextIcon from '@hugeicons/core-free-icons/ReceiptTextIcon';
import RefreshCcwIcon from '@hugeicons/core-free-icons/RefreshCcwIcon';
import RefreshCwIcon from '@hugeicons/core-free-icons/RefreshCwIcon';
import RepeatIcon from '@hugeicons/core-free-icons/RepeatIcon';
import RotateCcwIcon from '@hugeicons/core-free-icons/RotateCcwIcon';
import RotateCwIcon from '@hugeicons/core-free-icons/RotateCwIcon';
import RulerIcon from '@hugeicons/core-free-icons/RulerIcon';
import SaveIcon from '@hugeicons/core-free-icons/SaveIcon';
import ScanFaceIcon from '@hugeicons/core-free-icons/ScanFaceIcon';
import ScanLineIcon from '@hugeicons/core-free-icons/ScanLineIcon';
import ScanSearchIcon from '@hugeicons/core-free-icons/ScanSearchIcon';
import ScissorsIcon from '@hugeicons/core-free-icons/ScissorsIcon';
import Scooter01Icon from '@hugeicons/core-free-icons/Scooter01Icon';
import ScrollTextIcon from '@hugeicons/core-free-icons/ScrollTextIcon';
import Search01Icon from '@hugeicons/core-free-icons/Search01Icon';
import SendIcon from '@hugeicons/core-free-icons/SendIcon';
import Settings01Icon from '@hugeicons/core-free-icons/Settings01Icon';
import Settings02Icon from '@hugeicons/core-free-icons/Settings02Icon';
import Share01Icon from '@hugeicons/core-free-icons/Share01Icon';
import Shield01Icon from '@hugeicons/core-free-icons/Shield01Icon';
import ShieldAlertIcon from '@hugeicons/core-free-icons/ShieldAlertIcon';
import ShieldCheckIcon from '@hugeicons/core-free-icons/ShieldCheckIcon';
import ShieldQuestionMarkIcon from '@hugeicons/core-free-icons/ShieldQuestionMarkIcon';
import ShoppingCart01Icon from '@hugeicons/core-free-icons/ShoppingCart01Icon';
import SkipForwardIcon from '@hugeicons/core-free-icons/SkipForwardIcon';
import SlashIcon from '@hugeicons/core-free-icons/SlashIcon';
import SlidersHorizontalIcon from '@hugeicons/core-free-icons/SlidersHorizontalIcon';
import SmartphoneIcon from '@hugeicons/core-free-icons/SmartphoneIcon';
import SmileIcon from '@hugeicons/core-free-icons/SmileIcon';
import SparklesIcon from '@hugeicons/core-free-icons/SparklesIcon';
import SplineIcon from '@hugeicons/core-free-icons/SplineIcon';
import SquareIcon from '@hugeicons/core-free-icons/SquareIcon';
import SquareUnlock01Icon from '@hugeicons/core-free-icons/SquareUnlock01Icon';
import StarIcon from '@hugeicons/core-free-icons/StarIcon';
import StethoscopeIcon from '@hugeicons/core-free-icons/StethoscopeIcon';
import StopCircleIcon from '@hugeicons/core-free-icons/StopCircleIcon';
import Sun01Icon from '@hugeicons/core-free-icons/Sun01Icon';
import Tablet01Icon from '@hugeicons/core-free-icons/Tablet01Icon';
import Tag01Icon from '@hugeicons/core-free-icons/Tag01Icon';
import Target01Icon from '@hugeicons/core-free-icons/Target01Icon';
import ThermometerIcon from '@hugeicons/core-free-icons/ThermometerIcon';
import Ticket01Icon from '@hugeicons/core-free-icons/Ticket01Icon';
import Timer01Icon from '@hugeicons/core-free-icons/Timer01Icon';
import ToggleLeftIcon from '@hugeicons/core-free-icons/ToggleLeftIcon';
import ToggleRightIcon from '@hugeicons/core-free-icons/ToggleRightIcon';
import TreePalmIcon from '@hugeicons/core-free-icons/TreePalmIcon';
import TrendingDownIcon from '@hugeicons/core-free-icons/TrendingDownIcon';
import TrendingUpIcon from '@hugeicons/core-free-icons/TrendingUpIcon';
import TriangleAlertIcon from '@hugeicons/core-free-icons/TriangleAlertIcon';
import TrophyIcon from '@hugeicons/core-free-icons/TrophyIcon';
import TruckIcon from '@hugeicons/core-free-icons/TruckIcon';
import Upload01Icon from '@hugeicons/core-free-icons/Upload01Icon';
import UserCheck01Icon from '@hugeicons/core-free-icons/UserCheck01Icon';
import UserCircleIcon from '@hugeicons/core-free-icons/UserCircleIcon';
import UserCogIcon from '@hugeicons/core-free-icons/UserCogIcon';
import UserIcon from '@hugeicons/core-free-icons/UserIcon';
import UserPenIcon from '@hugeicons/core-free-icons/UserPenIcon';
import UserPlusIcon from '@hugeicons/core-free-icons/UserPlusIcon';
import UserRoundSearchIcon from '@hugeicons/core-free-icons/UserRoundSearchIcon';
import UserXIcon from '@hugeicons/core-free-icons/UserXIcon';
import UsersIcon from '@hugeicons/core-free-icons/UsersIcon';
import Video01Icon from '@hugeicons/core-free-icons/Video01Icon';
import VolumeHighIcon from '@hugeicons/core-free-icons/VolumeHighIcon';
import Wallet01Icon from '@hugeicons/core-free-icons/Wallet01Icon';
import WarehouseIcon from '@hugeicons/core-free-icons/WarehouseIcon';
import Watch01Icon from '@hugeicons/core-free-icons/Watch01Icon';
import WavesIcon from '@hugeicons/core-free-icons/WavesIcon';
import Wifi01Icon from '@hugeicons/core-free-icons/Wifi01Icon';
import WifiOff01Icon from '@hugeicons/core-free-icons/WifiOff01Icon';
import WindIcon from '@hugeicons/core-free-icons/WindIcon';
import WorkflowIcon from '@hugeicons/core-free-icons/WorkflowIcon';
import Wrench01Icon from '@hugeicons/core-free-icons/Wrench01Icon';
import XIcon from '@hugeicons/core-free-icons/XIcon';
import ZapIcon from '@hugeicons/core-free-icons/ZapIcon';

export type IconProps = Omit<HugeiconsProps, 'icon'>;
/** Lucide'ın `LucideIcon` tipini kullanan yerler (istasyon kayıtları) için karşılık. */
export type LucideIcon = React.FC<IconProps>;

/** Lucide adıyla çağrılan, HugeIcons çizen bileşen üretir. */
function make(icon: HugeiconsProps['icon'], name: string): React.FC<IconProps> {
  const C = (props: IconProps) => <HugeiconsIcon icon={icon} {...props} />;
  C.displayName = name;
  return C;
}

export const Activity = make(Activity01Icon, 'Activity');
export const AlarmClock = make(AlarmClockIcon, 'AlarmClock');
export const AlertCircle = make(AlertCircleIcon, 'AlertCircle');
export const AlertOctagon = make(AlertDiamondIcon, 'AlertOctagon');
export const AlertTriangle = make(Alert02Icon, 'AlertTriangle');
export const Archive = make(ArchiveIcon, 'Archive');
export const ArrowDown = make(ArrowDown01Icon, 'ArrowDown');
export const ArrowDownCircle = make(CircleArrowDown01Icon, 'ArrowDownCircle');
export const ArrowDownLeft = make(ArrowDownLeft01Icon, 'ArrowDownLeft');
export const ArrowDownToLine = make(ArrowDownToLineIcon, 'ArrowDownToLine');
export const ArrowLeft = make(ArrowLeft01Icon, 'ArrowLeft');
export const ArrowLeftRight = make(ArrowLeftRightIcon, 'ArrowLeftRight');
export const ArrowRight = make(ArrowRight01Icon, 'ArrowRight');
export const ArrowRightLeft = make(ArrowDataTransferHorizontalIcon, 'ArrowRightLeft');
export const ArrowUp = make(ArrowUp01Icon, 'ArrowUp');
export const ArrowUpCircle = make(CircleArrowUp01Icon, 'ArrowUpCircle');
export const ArrowUpDown = make(ArrowUpDownIcon, 'ArrowUpDown');
export const ArrowUpLeft = make(ArrowUpLeft01Icon, 'ArrowUpLeft');
export const ArrowUpRight = make(ArrowUpRight01Icon, 'ArrowUpRight');
export const Atom = make(Atom01Icon, 'Atom');
export const Award = make(Award01Icon, 'Award');
export const BadgeCheck = make(BadgeCheckIcon, 'BadgeCheck');
export const Ban = make(BanIcon, 'Ban');
export const Banknote = make(BanknoteIcon, 'Banknote');
export const BarChart2 = make(BarChartIcon, 'BarChart2');
export const BarChart3 = make(ChartBarIncreasingIcon, 'BarChart3');
export const Beaker = make(BeakerIcon, 'Beaker');
export const Bell = make(BellIcon, 'Bell');
export const BellOff = make(BellOffIcon, 'BellOff');
export const BellRing = make(BellRingIcon, 'BellRing');
export const Bike = make(BikeIcon, 'Bike');
export const BookOpen = make(BookOpen01Icon, 'BookOpen');
export const Bot = make(BotIcon, 'Bot');
export const Box = make(BoxIcon, 'Box');
export const Boxes = make(BoxesIcon, 'Boxes');
export const Briefcase = make(Briefcase01Icon, 'Briefcase');
export const Brush = make(BrushIcon, 'Brush');
export const Bug = make(Bug01Icon, 'Bug');
export const Building = make(BuildingIcon, 'Building');
export const Building2 = make(Building03Icon, 'Building2');
export const Calculator = make(CalculatorIcon, 'Calculator');
export const Calendar = make(Calendar01Icon, 'Calendar');
export const CalendarCheck = make(CalendarCheckIcon, 'CalendarCheck');
export const CalendarClock = make(CalendarClockIcon, 'CalendarClock');
export const CalendarDays = make(CalendarDaysIcon, 'CalendarDays');
export const CalendarHeart = make(CalendarHeartIcon, 'CalendarHeart');
export const CalendarPlus = make(CalendarPlusIcon, 'CalendarPlus');
export const Camera = make(Camera01Icon, 'Camera');
export const Check = make(CheckIcon, 'Check');
export const CheckCheck = make(CheckCheckIcon, 'CheckCheck');
export const CheckCircle = make(CheckmarkCircle01Icon, 'CheckCircle');
export const CheckCircle2 = make(CheckmarkCircle02Icon, 'CheckCircle2');
export const CheckSquare = make(CheckmarkSquare01Icon, 'CheckSquare');
export const ChevronDown = make(ChevronDownIcon, 'ChevronDown');
export const ChevronLeft = make(ChevronLeftIcon, 'ChevronLeft');
export const ChevronRight = make(ChevronRightIcon, 'ChevronRight');
export const ChevronUp = make(ChevronUpIcon, 'ChevronUp');
export const Circle = make(CircleIcon, 'Circle');
export const CircleCheck = make(CircleCheckIcon, 'CircleCheck');
export const CircleDollarSign = make(CircleDollarSignIcon, 'CircleDollarSign');
export const CircleDot = make(CircleDotIcon, 'CircleDot');
export const CircleX = make(CircleXIcon, 'CircleX');
export const Clipboard = make(ClipboardIcon, 'Clipboard');
export const ClipboardCheck = make(ClipboardCheckIcon, 'ClipboardCheck');
export const ClipboardList = make(ClipboardListIcon, 'ClipboardList');
export const ClipboardX = make(ClipboardXIcon, 'ClipboardX');
export const Clock = make(Clock01Icon, 'Clock');
export const CloudUpload = make(CloudUploadIcon, 'CloudUpload');
export const Cog = make(CogIcon, 'Cog');
export const Coins = make(Coins01Icon, 'Coins');
export const Columns3 = make(Grid3X3Icon, 'Columns3');
export const CookingPot = make(CookingPotIcon, 'CookingPot');
export const Copy = make(CopyIcon, 'Copy');
export const CornerDownLeft = make(CornerDownLeftIcon, 'CornerDownLeft');
export const CornerDownRight = make(CornerDownRightIcon, 'CornerDownRight');
export const CornerUpLeft = make(CornerUpLeftIcon, 'CornerUpLeft');
export const Cpu = make(CpuIcon, 'Cpu');
export const CreditCard = make(CreditCardIcon, 'CreditCard');
export const Crosshair = make(CrosshairIcon, 'Crosshair');
export const Database = make(DatabaseIcon, 'Database');
export const DatabaseZap = make(DatabaseZapIcon, 'DatabaseZap');
export const Delete = make(Delete01Icon, 'Delete');
export const Diamond = make(DiamondIcon, 'Diamond');
export const DollarSign = make(DollarSignIcon, 'DollarSign');
export const Download = make(Download01Icon, 'Download');
export const Drill = make(DrillIcon, 'Drill');
export const Droplets = make(DropletsIcon, 'Droplets');
export const Edit2 = make(PencilEdit01Icon, 'Edit2');
export const Edit3 = make(Edit02Icon, 'Edit3');
export const Equal = make(EqualIcon, 'Equal');
export const Eraser = make(EraserIcon, 'Eraser');
export const ExternalLink = make(ExternalLinkIcon, 'ExternalLink');
export const Eye = make(EyeIcon, 'Eye');
export const EyeOff = make(EyeOffIcon, 'EyeOff');
export const File = make(File01Icon, 'File');
export const FileArchive = make(FileArchiveIcon, 'FileArchive');
export const FileAudio = make(FileAudioIcon, 'FileAudio');
export const FileBox = make(FileBoxIcon, 'FileBox');
export const FileCheck = make(FileCheckIcon, 'FileCheck');
export const FileClock = make(FileClockIcon, 'FileClock');
export const FileDown = make(FileDownIcon, 'FileDown');
export const FileEdit = make(FileEditIcon, 'FileEdit');
export const FileMinus = make(FileMinusIcon, 'FileMinus');
export const FilePlus = make(FilePlusIcon, 'FilePlus');
export const FilePlus2 = make(FileAddIcon, 'FilePlus2');
export const FileSearch = make(FileSearchIcon, 'FileSearch');
export const FileSpreadsheet = make(FileSpreadsheetIcon, 'FileSpreadsheet');
export const FileText = make(FileTextIcon, 'FileText');
export const FileUp = make(FileUpIcon, 'FileUp');
export const FileVideo = make(FileVideoIcon, 'FileVideo');
export const FileWarning = make(FileValidationIcon, 'FileWarning');
export const FileX = make(FileXIcon, 'FileX');
export const Film = make(Film01Icon, 'Film');
export const Filter = make(FilterIcon, 'Filter');
export const Flame = make(FlameIcon, 'Flame');
export const Flashlight = make(FlashlightIcon, 'Flashlight');
export const FlaskConical = make(FlaskConicalIcon, 'FlaskConical');
export const FlipHorizontal2 = make(FlipHorizontalIcon, 'FlipHorizontal2');
export const Focus = make(FocusIcon, 'Focus');
export const Folder = make(Folder01Icon, 'Folder');
export const FolderOpen = make(FolderOpenIcon, 'FolderOpen');
export const Funnel = make(FunnelIcon, 'Funnel');
export const Gauge = make(GaugeIcon, 'Gauge');
export const Gem = make(GemIcon, 'Gem');
export const GitMerge = make(GitMergeIcon, 'GitMerge');
export const Globe = make(GlobeIcon, 'Globe');
export const GraduationCap = make(GraduationCapIcon, 'GraduationCap');
export const Grid = make(GridIcon, 'Grid');
export const Grid3x3 = make(Grid3X3Icon, 'Grid3x3');
export const GripVertical = make(GripVerticalIcon, 'GripVertical');
export const Hammer = make(HammerIcon, 'Hammer');
export const Hand = make(HandIcon, 'Hand');
export const Hash = make(HashIcon, 'Hash');
export const Headphones = make(HeadphonesIcon, 'Headphones');
export const Heart = make(HeartIcon, 'Heart');
export const HelpCircle = make(HelpCircleIcon, 'HelpCircle');
export const History = make(HistoryIcon, 'History');
export const Home = make(Home01Icon, 'Home');
export const Hourglass = make(HourglassIcon, 'Hourglass');
export const Image = make(Image01Icon, 'Image');
export const ImageDown = make(ImageDownIcon, 'ImageDown');
export const ImageOff = make(ImageOffIcon, 'ImageOff');
export const ImagePlus = make(ImagePlusIcon, 'ImagePlus');
export const Inbox = make(InboxIcon, 'Inbox');
export const Info = make(InfoIcon, 'Info');
export const KeyRound = make(KeyRoundIcon, 'KeyRound');
export const Landmark = make(LandmarkIcon, 'Landmark');
export const Laptop = make(LaptopIcon, 'Laptop');
export const Layers = make(Layers01Icon, 'Layers');
export const LayoutDashboard = make(LayoutDashboardIcon, 'LayoutDashboard');
export const LayoutGrid = make(LayoutGridIcon, 'LayoutGrid');
export const LayoutList = make(LayoutListIcon, 'LayoutList');
export const Lightbulb = make(LightbulbIcon, 'Lightbulb');
export const Link = make(LinkIcon, 'Link');
export const Link2 = make(Link02Icon, 'Link2');
export const List = make(ListIcon, 'List');
export const ListCheck = make(CheckListIcon, 'ListCheck');
export const ListChecks = make(ListChecksIcon, 'ListChecks');
export const ListPlus = make(ListPlusIcon, 'ListPlus');
export const ListTodo = make(ListTodoIcon, 'ListTodo');
export const Loader = make(LoaderIcon, 'Loader');
export const Loader2 = make(Loading03Icon, 'Loader2');
export const Locate = make(LocateIcon, 'Locate');
export const Lock = make(LockIcon, 'Lock');
export const LogIn = make(LogInIcon, 'LogIn');
export const LogOut = make(LogOutIcon, 'LogOut');
export const Magnet = make(MagnetIcon, 'Magnet');
export const Mail = make(Mail01Icon, 'Mail');
export const MailWarning = make(MailWarningIcon, 'MailWarning');
export const Map = make(MapIcon, 'Map');
export const MapPin = make(MapPinIcon, 'MapPin');
export const MapPinCheck = make(MapPinCheckIcon, 'MapPinCheck');
export const MapPinOff = make(MapPinOffIcon, 'MapPinOff');
export const Maximize2 = make(Maximize01Icon, 'Maximize2');
export const Megaphone = make(Megaphone01Icon, 'Megaphone');
export const Menu = make(MenuIcon, 'Menu');
export const MessageCircle = make(MessageCircleIcon, 'MessageCircle');
export const MessageCirclePlus = make(MessageCirclePlusIcon, 'MessageCirclePlus');
export const MessageSquare = make(MessageSquareIcon, 'MessageSquare');
export const MessagesSquare = make(MessagesSquareIcon, 'MessagesSquare');
export const Mic = make(Mic01Icon, 'Mic');
export const MicOff = make(MicOff01Icon, 'MicOff');
export const Microscope = make(MicroscopeIcon, 'Microscope');
export const Microwave = make(MicrowaveIcon, 'Microwave');
export const Minus = make(MinusIcon, 'Minus');
export const MinusCircle = make(MinusSignCircleIcon, 'MinusCircle');
export const Monitor = make(MonitorIcon, 'Monitor');
export const Moon = make(MoonIcon, 'Moon');
export const MoreHorizontal = make(MoreHorizontalIcon, 'MoreHorizontal');
export const MoveHorizontal = make(MoveHorizontalIcon, 'MoveHorizontal');
export const MoveUpRight = make(MoveUpRightIcon, 'MoveUpRight');
export const Navigation = make(NavigationIcon, 'Navigation');
export const Network = make(NetworkIcon, 'Network');
export const Package = make(PackageIcon, 'Package');
export const PackageCheck = make(PackageCheckIcon, 'PackageCheck');
export const PackageOpen = make(PackageOpenIcon, 'PackageOpen');
export const Paintbrush = make(PaintbrushIcon, 'Paintbrush');
export const Palette = make(PaletteIcon, 'Palette');
export const Palmtree = make(TreePalmIcon, 'Palmtree');
export const PanelLeft = make(PanelLeftIcon, 'PanelLeft');
export const Paperclip = make(PaperclipIcon, 'Paperclip');
export const Pause = make(PauseIcon, 'Pause');
export const PauseCircle = make(PauseCircleIcon, 'PauseCircle');
export const PenLine = make(PenLineIcon, 'PenLine');
export const PenTool = make(PenTool01Icon, 'PenTool');
export const Pencil = make(PencilEdit01Icon, 'Pencil');
export const Percent = make(PercentIcon, 'Percent');
export const Phone = make(PhoneIcon, 'Phone');
export const PhoneCall = make(PhoneCallIcon, 'PhoneCall');
export const PieChart = make(PieChartIcon, 'PieChart');
export const Pin = make(PinIcon, 'Pin');
export const Play = make(PlayIcon, 'Play');
export const PlayCircle = make(PlayCircleIcon, 'PlayCircle');
export const Plug = make(PlugIcon, 'Plug');
export const Plus = make(PlusIcon, 'Plus');
export const PlusCircle = make(PlusSignCircleIcon, 'PlusCircle');
export const Power = make(PowerIcon, 'Power');
export const Printer = make(PrinterIcon, 'Printer');
export const Puzzle = make(PuzzleIcon, 'Puzzle');
export const QrCode = make(QrCodeIcon, 'QrCode');
export const Receipt = make(ReceiptIcon, 'Receipt');
export const ReceiptText = make(ReceiptTextIcon, 'ReceiptText');
export const RefreshCcw = make(RefreshCcwIcon, 'RefreshCcw');
export const RefreshCw = make(RefreshCwIcon, 'RefreshCw');
export const Repeat = make(RepeatIcon, 'Repeat');
export const Repeat2 = make(RepeatIcon, 'Repeat2');
export const RotateCcw = make(RotateCcwIcon, 'RotateCcw');
export const RotateCw = make(RotateCwIcon, 'RotateCw');
export const Ruler = make(RulerIcon, 'Ruler');
export const Save = make(SaveIcon, 'Save');
export const ScanFace = make(ScanFaceIcon, 'ScanFace');
export const ScanLine = make(ScanLineIcon, 'ScanLine');
export const ScanSearch = make(ScanSearchIcon, 'ScanSearch');
export const Scissors = make(ScissorsIcon, 'Scissors');
export const Scooter = make(Scooter01Icon, 'Scooter');
export const ScrollText = make(ScrollTextIcon, 'ScrollText');
export const Search = make(Search01Icon, 'Search');
export const Send = make(SendIcon, 'Send');
export const Settings = make(Settings01Icon, 'Settings');
export const Settings2 = make(Settings02Icon, 'Settings2');
export const Share2 = make(Share01Icon, 'Share2');
export const Shield = make(Shield01Icon, 'Shield');
export const ShieldAlert = make(ShieldAlertIcon, 'ShieldAlert');
export const ShieldCheck = make(ShieldCheckIcon, 'ShieldCheck');
export const ShieldQuestion = make(ShieldQuestionMarkIcon, 'ShieldQuestion');
export const ShoppingCart = make(ShoppingCart01Icon, 'ShoppingCart');
export const SkipForward = make(SkipForwardIcon, 'SkipForward');
export const Slash = make(SlashIcon, 'Slash');
export const Sliders = make(SlidersHorizontalIcon, 'Sliders');
export const SlidersHorizontal = make(SlidersHorizontalIcon, 'SlidersHorizontal');
export const Smartphone = make(SmartphoneIcon, 'Smartphone');
export const Smile = make(SmileIcon, 'Smile');
export const Sparkles = make(SparklesIcon, 'Sparkles');
export const Spline = make(SplineIcon, 'Spline');
export const Square = make(SquareIcon, 'Square');
export const Star = make(StarIcon, 'Star');
export const Stethoscope = make(StethoscopeIcon, 'Stethoscope');
export const StopCircle = make(StopCircleIcon, 'StopCircle');
export const Sun = make(Sun01Icon, 'Sun');
export const Tablet = make(Tablet01Icon, 'Tablet');
export const Tag = make(Tag01Icon, 'Tag');
export const Target = make(Target01Icon, 'Target');
export const Thermometer = make(ThermometerIcon, 'Thermometer');
export const Ticket = make(Ticket01Icon, 'Ticket');
export const Timer = make(Timer01Icon, 'Timer');
export const ToggleLeft = make(ToggleLeftIcon, 'ToggleLeft');
export const ToggleRight = make(ToggleRightIcon, 'ToggleRight');
export const Trash2 = make(Delete02Icon, 'Trash2');
export const TrendingDown = make(TrendingDownIcon, 'TrendingDown');
export const TrendingUp = make(TrendingUpIcon, 'TrendingUp');
export const TriangleAlert = make(TriangleAlertIcon, 'TriangleAlert');
export const Trophy = make(TrophyIcon, 'Trophy');
export const Truck = make(TruckIcon, 'Truck');
export const Undo2 = make(ArrowTurnBackwardIcon, 'Undo2');
export const Unlock = make(SquareUnlock01Icon, 'Unlock');
export const Upload = make(Upload01Icon, 'Upload');
export const UploadCloud = make(CloudUploadIcon, 'UploadCloud');
export const User = make(UserIcon, 'User');
export const UserCheck = make(UserCheck01Icon, 'UserCheck');
export const UserCircle = make(UserCircleIcon, 'UserCircle');
export const UserCog = make(UserCogIcon, 'UserCog');
export const UserPen = make(UserPenIcon, 'UserPen');
export const UserPlus = make(UserPlusIcon, 'UserPlus');
export const UserRoundSearch = make(UserRoundSearchIcon, 'UserRoundSearch');
export const UserX = make(UserXIcon, 'UserX');
export const Users = make(UsersIcon, 'Users');
export const Video = make(Video01Icon, 'Video');
export const Volume2 = make(VolumeHighIcon, 'Volume2');
export const Wallet = make(Wallet01Icon, 'Wallet');
export const Wand2 = make(MagicWand01Icon, 'Wand2');
export const Warehouse = make(WarehouseIcon, 'Warehouse');
export const Watch = make(Watch01Icon, 'Watch');
export const Waves = make(WavesIcon, 'Waves');
export const Wifi = make(Wifi01Icon, 'Wifi');
export const WifiOff = make(WifiOff01Icon, 'WifiOff');
export const Wind = make(WindIcon, 'Wind');
export const Workflow = make(WorkflowIcon, 'Workflow');
export const Wrench = make(Wrench01Icon, 'Wrench');
export const X = make(XIcon, 'X');
export const XCircle = make(CancelCircleIcon, 'XCircle');
export const Zap = make(ZapIcon, 'Zap');
